mapNames = { ...
    'thermal','haline','solar','ice','gray', ...
    'oxy','deep','dense','algae','matter','turbid', ...
    'speed','amp','tempo','rain','phase','topo', ...
    'balance','delta','curl','diff','tarn'};
for k = 1:numel(mapNames)
    name = mapNames{k};
    cmap = cmocean(name,256);
    assignin('base', ['cmap_' name], cmap);
end
