function profile = FCS_getTypographyProfile(profileName)
% FCS_getTypographyProfile Return FontName profile definition for FCS typography pass.

    if nargin < 1 || isempty(profileName)
        profileName = "Default";
    end

    name = lower(strtrim(string(profileName)));

    switch name
        case {"default"}
            profile = struct( ...
                'Name', "Default", ...
                'FontName', "", ...
                'Fallbacks', strings(0,1));

        case {"prl/aps", "prl", "aps"}
            profile = struct( ...
                'Name', "PRL/APS", ...
                'FontName', "Times New Roman", ...
                'Fallbacks', ["Times"; "Times-Roman"; "Nimbus Roman"]);

        case {"nature"}
            profile = struct( ...
                'Name', "Nature", ...
                'FontName', "Helvetica", ...
                'Fallbacks', ["Arial"; "Liberation Sans"; "Nimbus Sans"]);

        case {"prb"}
            profile = struct( ...
                'Name', "PRB", ...
                'FontName', "Times New Roman", ...
                'Fallbacks', ["Times"; "Times-Roman"; "Nimbus Roman"]);

        otherwise
            error('FCS_getTypographyProfile:UnknownProfile', 'Unknown typography profile: %s', string(profileName));
    end
end
