function fig = create_figure(varargin)
% create_figure Create a publication-style figure with repository defaults.

font_name = resolve_publication_font();
default_position = [2 2 8.6 6.2];

fig = figure('Color', 'w', ...
    'Units', 'centimeters', ...
    'Position', default_position, ...
    'PaperUnits', 'centimeters', ...
    'PaperPosition', [0 0 default_position(3) default_position(4)], ...
    'PaperSize', [default_position(3) default_position(4)], ...
    'InvertHardcopy', 'off', ...
    'DefaultAxesFontName', font_name, ...
    'DefaultTextFontName', font_name, ...
    'DefaultAxesFontSize', 8, ...
    'DefaultLegendFontSize', 8, ...
    'DefaultAxesTickDir', 'out', ...
    'DefaultAxesLineWidth', 1, ...
    'DefaultAxesLayer', 'top', ...
    'DefaultAxesBox', 'off', ...
    'DefaultAxesXMinorTick', 'off', ...
    'DefaultAxesYMinorTick', 'off', ...
    'DefaultAxesTickLabelInterpreter', 'tex', ...
    'DefaultTextInterpreter', 'tex', ...
    'DefaultLegendInterpreter', 'tex', ...
    'DefaultLineLineWidth', 2, ...
    varargin{:});

normalize_paper_size(fig);
end

function normalize_paper_size(fig)
set(fig, 'Units', 'centimeters');
pos = get(fig, 'Position');
if numel(pos) ~= 4 || any(~isfinite(pos(3:4))) || any(pos(3:4) <= 0)
    pos = [2 2 8.6 6.2];
    set(fig, 'Position', pos);
end
set(fig, 'PaperUnits', 'centimeters', ...
    'PaperPosition', [0 0 pos(3) pos(4)], ...
    'PaperSize', [pos(3) pos(4)]);
end

function font_name = resolve_publication_font()
font_name = 'Helvetica';
try
    fonts = listfonts;
    if ~any(strcmpi(fonts, font_name)) && any(strcmpi(fonts, 'Arial'))
        font_name = 'Arial';
    end
catch
    font_name = 'Arial';
end
end
