function addGradientTempArrowExact(ax,Tmin,Tmax)

if nargin<1 || isempty(ax)
    ax = gca;
end

fig = ancestor(ax,'figure');
pos = ax.Position;     % normalized

% ===== PRL tuning =====
arrowHeight = 0.025;
gap = 0.018;

x0 = pos(1);
x1 = pos(1) + pos(3);

y0 = pos(2) - gap - arrowHeight;
y1 = pos(2) - gap;

% ----- gradient body -----
n = 600;
x = linspace(x0,x1,n);
y = [y0 y1];

[X,Y] = meshgrid(x,y);
C = repmat(linspace(0,1,n),2,1);

surface('XData',X,'YData',Y,'ZData',zeros(size(X)), ...
        'CData',C, ...
        'EdgeColor','none', ...
        'FaceColor','interp', ...
        'Units','normalized', ...
        'Parent',fig);

% copy colormap
cmap = colormap(ax);
colormap(fig,cmap);

% ----- arrow head -----
headW = (x1-x0)*0.02;

patch('XData',[x1 x1 x1+headW], ...
      'YData',[y0 y1 (y0+y1)/2], ...
      'FaceColor', cmap(end,:), ...
      'EdgeColor','none', ...
      'Units','normalized', ...
      'Parent',fig);

% ----- labels -----
fs = ax.FontSize;

annotation(fig,'textbox',[x0 y0-0.035 0.05 0.03], ...
    'String',sprintf('$%g\\,\\mathrm{K}$',Tmin), ...
    'Interpreter','latex', ...
    'LineStyle','none', ...
    'FontSize',fs);

annotation(fig,'textbox',[x1-0.05 y0-0.035 0.06 0.03], ...
    'String',sprintf('$%g\\,\\mathrm{K}$',Tmax), ...
    'Interpreter','latex', ...
    'LineStyle','none', ...
    'HorizontalAlignment','right', ...
    'FontSize',fs);

annotation(fig,'textbox',[pos(1)+pos(3)/2-0.1 y0-0.065 0.2 0.03], ...
    'String','$\mathrm{Temperature\ (K)}$', ...
    'Interpreter','latex', ...
    'HorizontalAlignment','center', ...
    'LineStyle','none', ...
    'FontSize',fs);

end
