function axLeg = renderCombinedLegendOverlayInParent(parentHandle, legendData)
axLeg = [];

if nargin < 2 || isempty(legendData)
    return;
end
if ~isfield(legendData, 'enabled') || ~logical(legendData.enabled)
    return;
end
if isempty(parentHandle) || ~isgraphics(parentHandle)
    return;
end

existing = findall(parentHandle, 'Type', 'axes', 'Tag', 'PlotsMTCombinedManualLegendAxes');
if ~isempty(existing)
    delete(existing);
end

layout = legendData.layout;
axLeg = axes('Parent', parentHandle, ...
    'Units', 'normalized', ...
    'Position', legendData.legendBoxNorm, ...
    'Color', 'none', ...
    'XColor', 'none', ...
    'YColor', 'none', ...
    'XLim', [0 1], ...
    'YLim', layout.yLim, ...
    'YDir', layout.yDir, ...
    'HitTest', 'on', ...
    'PickableParts', 'all', ...
    'HandleVisibility', 'on', ...
    'Visible', 'on', ...
    'Tag', 'PlotsMTCombinedManualLegendAxes', ...
    'Clipping', 'off');

try
    uistack(axLeg, 'top');
catch
end

text(axLeg, layout.xHeaderZFC, layout.headerY, 'ZFC', ...
    'FontWeight', 'normal', ...
    'Interpreter', 'latex', ...
    'FontSize', legendData.fontsize - 2, ...
    'HitTest', 'on', ...
    'PickableParts', 'all');

text(axLeg, layout.xHeaderFCW, layout.headerY, 'FCW', ...
    'FontWeight', 'normal', ...
    'Interpreter', 'latex', ...
    'FontSize', legendData.fontsize - 2, ...
    'HitTest', 'on', ...
    'PickableParts', 'all');

nLegend = numel(legendData.fieldsSortedTesla);
for k = 1:nLegend
    idx = legendData.orderDescend(k);
    y = layout.rowY0 + k * layout.rowSpacing;

    zfcColor = legendData.colorsZFC(legendData.fieldRank(idx), :);
    fcwColor = legendData.colorsFCW(legendData.fieldRank(idx), :);

    line(axLeg, layout.xZFCLine, [y y], ...
        'Color', zfcColor, ...
        'LineWidth', legendData.lw, ...
        'HitTest', 'on', ...
        'PickableParts', 'all');

    line(axLeg, layout.xFCWLine, [y y], ...
        'Color', fcwColor, ...
        'LineWidth', legendData.lw, ...
        'HitTest', 'on', ...
        'PickableParts', 'all');

    text(axLeg, layout.xText, y, sprintf('%.1f T', legendData.fieldsSortedTesla(k)), ...
        'HorizontalAlignment', 'left', ...
        'Interpreter', 'latex', ...
        'FontSize', legendData.fontsize - 4, ...
        'HitTest', 'on', ...
        'PickableParts', 'all');
end
end
