% One-shot builder: generates Aging/diagnostics/aging_F6I_legacy_tau_from_curve.m from aging_timescale_extraction.m.
repoRoot = fileparts(fileparts(mfilename('fullpath')));
srcPath = fullfile(repoRoot, 'Aging', 'analysis', 'aging_timescale_extraction.m');
dstPath = fullfile(repoRoot, 'Aging', 'diagnostics', 'aging_F6I_legacy_tau_from_curve.m');

txt = fileread(srcPath);
lines = splitlines(txt);

hdr = sprintf([ ...
    'function out = aging_F6I_legacy_tau_from_curve(tw, y)\n' ...
    '%%AGING_F6I_LEGACY_TAU_FROM_CURVE Diagnostic-only tau extraction aligned with aging_timescale_extraction.m.\n' ...
    '%% Labels: diagnostic_tau_only not_canonical not_physical_claim not_replacing_F4A_F4B\n' ...
    'tw = tw(:);\n' ...
    'y = y(:);\n' ...
    'row = f6i_analyzeTpGroup(tw, y);\n' ...
    'out = f6i_rowToOut(row);\n' ...
    'end\n\n' ...
    'function out = f6i_rowToOut(row)\n' ...
    'out.tau_diagnostic_consensus_seconds = row.tau_effective_seconds;\n' ...
    'out.tau_consensus_method_count = row.tau_consensus_method_count;\n' ...
    'out.tau_consensus_methods = row.tau_consensus_methods;\n' ...
    'out.tau_method_spread_decades = row.tau_method_spread_decades;\n' ...
    'out.tau_logistic_half_seconds = row.tau_logistic_half_seconds;\n' ...
    'out.tau_logistic_trusted = row.tau_logistic_trusted;\n' ...
    'out.tau_logistic_rmse = row.tau_logistic_rmse;\n' ...
    'out.tau_logistic_r2 = row.tau_logistic_r2;\n' ...
    'out.tau_logistic_status = row.tau_logistic_status;\n' ...
    'out.tau_stretched_half_seconds = row.tau_stretched_half_seconds;\n' ...
    'out.tau_stretched_trusted = row.tau_stretched_trusted;\n' ...
    'out.tau_stretched_rmse = row.tau_stretched_rmse;\n' ...
    'out.tau_stretched_r2 = row.tau_stretched_r2;\n' ...
    'out.tau_stretched_status = row.tau_stretched_status;\n' ...
    'out.tau_stretched_beta = row.tau_stretched_beta;\n' ...
    'out.tau_half_range_seconds = row.tau_half_range_seconds;\n' ...
    'out.tau_half_range_status = row.tau_half_range_status;\n' ...
    'out.n_points = row.n_points;\n' ...
    'out.n_downturns = row.n_downturns;\n' ...
    'end\n\n' ]);

core = strjoin(lines(170:213), newline);
core = strrep(core, 'row.Tp = sub.Tp(1);', 'row.Tp = NaN;');
core = strrep(core, 'row.source_run = sub.source_run(1);', 'row.source_run = "diagnostic";');

bodyAg = sprintf('function row = f6i_analyzeTpGroup(tw, y)\nrow = initTauRow();\ntw = tw(:);\ny = y(:);\n%s\nend\n\n', core);

initRowBlock = strjoin(lines(131:163), newline);
mid = strjoin(lines(216:446), newline);
tail = strjoin(lines(715:801), newline);

whole = sprintf('%s%s%s\n%s\n\n%s', hdr, bodyAg, initRowBlock, mid, tail);
fid = fopen(dstPath, 'w');
assert(fid >= 0, 'write failed');
fprintf(fid, '%s', whole);
fclose(fid);
fprintf('Wrote %s\n', dstPath);
