function ok = run_aging_F7G_metadata_contract_check()
%RUN_AGING_F7G_METADATA_CONTRACT_CHECK Verify appendF7GTauRMetadataColumns adds all F7G fields.
% ASCII-only. No physics; builds a one-row dummy table.

thisDir = fileparts(mfilename('fullpath'));
agingRoot = fullfile(thisDir, '..');
addpath(genpath(agingRoot));

tb = table(1, 'VariableNames', {'dummy_numeric'});
meta = struct( ...
    'writer_family_id', 'WF_TAU_DIP_CURVEFIT', ...
    'tau_or_R_flag', 'TAU', ...
    'tau_domain', 'SMOKE', ...
    'tau_input_observable_identities', '{}', ...
    'tau_input_observable_family', 'SMOKE', ...
    'source_writer_script', 'Aging/validation/run_aging_F7G_metadata_contract_check.m', ...
    'source_artifact_basename', 'dummy.csv', ...
    'source_artifact_path', 'SMOKE_PATH', ...
    'canonical_status', 'smoke', ...
    'model_use_allowed', 'NO', ...
    'semantic_status', 'SMOKE', ...
    'lineage_status', 'SMOKE');

tb2 = appendF7GTauRMetadataColumns(tb, meta);

req = {'writer_family_id','tau_or_R_flag','tau_domain','tau_input_observable_identities', ...
    'tau_input_observable_family','source_writer_script','source_artifact_basename', ...
    'source_artifact_path','canonical_status','model_use_allowed','semantic_status','lineage_status'};
ok = all(ismember(req, tb2.Properties.VariableNames)) && height(tb2) == 1;

end
