function [SampleTempKelvin, SampHCJK] = importOneFileACHC(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [SAMPLETEMPKELVIN, SAMPHCJK] = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as
%  column vectors.
%
%  [SAMPLETEMPKELVIN, SAMPHCJK] = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [SampleTempKelvin, SampHCJK] = importfile("H:\My Drive\Quantum materials lab\Projects\Magnetic Intercalated TMD\Co1_3TaS2\MG 131\MG 131 HC1 DC Heat capacity\Field Scan 0T to 14T Data\MG131 7p71mg 0T.Dat", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Sep-2024 15:18:02

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 30);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "SampleTempKelvin", "Var9", "SampHCJK", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30"];
opts.SelectedVariableNames = ["SampleTempKelvin", "SampHCJK"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "double", "string", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var9", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var9", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
SampleTempKelvin = tbl.SampleTempKelvin;
SampHCJK = tbl.SampHCJK;
end