function style = getPlotStylePreset(presetName)
if nargin < 1 || isempty(presetName)
    presetName = 'paper';
end

if isstring(presetName)
    if ~isscalar(presetName)
        error('getPlotStylePreset:InvalidPresetName', 'presetName must be a scalar string or char.');
    end
    presetName = char(presetName);
elseif ~ischar(presetName)
    error('getPlotStylePreset:InvalidPresetName', 'presetName must be a scalar string or char.');
end

switch lower(strtrim(presetName))
    case 'paper'
        style = struct( ...
            'fontSize', 17, ...
            'interpreter', 'latex', ...
            'fontWeight', 'normal', ...
            'titleFontSizeMultiplier', 1.05, ...
            'axisBox', 'on', ...
            'gridPolicy', 'off', ...
            'tickLabelInterpreter', 'latex', ...
            'legendInterpreter', 'latex');
    case 'compact'
        style = struct( ...
            'fontSize', 15, ...
            'interpreter', 'latex', ...
            'fontWeight', 'normal', ...
            'titleFontSizeMultiplier', 1.00, ...
            'axisBox', 'on', ...
            'gridPolicy', 'off', ...
            'tickLabelInterpreter', 'latex', ...
            'legendInterpreter', 'latex');
    otherwise
        error('getPlotStylePreset:UnknownPreset', 'Unknown preset "%s".', presetName);
end
end
