% plot_aging_existing_figures_with_annotations
% Reuse existing Aging pipeline plotting functions (no reimplementation),
% then annotate and export combined artifacts.

repoRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(fullfile(repoRoot, 'Aging')));

figDir = fullfile(repoRoot, 'figures');
repDir = fullfile(repoRoot, 'reports');
if ~exist(figDir, 'dir'), mkdir(figDir); end
if ~exist(repDir, 'dir'), mkdir(repDir); end

figOutFig = fullfile(figDir, 'aging_existing_pipeline_decomposition.fig');
figOutPng = fullfile(figDir, 'aging_existing_pipeline_decomposition.png');
reportOut = fullfile(repDir, 'aging_deltam_decomposition_existing_plot.md');

plotSources = discoverPlotSources(repoRoot);
[state, cfg, dataLog] = loadOrBuildState(repoRoot);
cfg = ensurePlotConfig(cfg, state);

if ~hasDecompositionFields(state.pauseRuns)
    state = stage4_analyzeAFM_FM(state, cfg);
end

% ---------------- Existing pipeline plot #1: DeltaM overview ----------------
figBefore = findall(groot, 'Type', 'figure');
plotAgingMemory(state.noPause_T, state.noPause_M, state.pauseRuns, cfg.color_scheme, ...
    cfg.fontsize, cfg.linewidth, cfg.sample_name, cfg.Bohar_units, ...
    cfg.offsetMode, cfg.offsetValue, cfg.dip_window_K, cfg.colorRange, cfg.useAutoYScale);
deltaFigCandidates = setdiff(findall(groot, 'Type', 'figure'), figBefore);
deltaFig = pickDeltaFigure(deltaFigCandidates);

% ---------------- Existing pipeline plot #2: AFM/FM decomposition ----------------
cfgDecomp = cfg;
cfgDecomp.showAllPauses_AFmFM = false;
cfgDecomp.examplePause_K = pickExamplePauseK(state.pauseRuns);

figBefore = findall(groot, 'Type', 'figure');
plotDecompositionExamples(state, cfgDecomp);
decompFigCandidates = setdiff(findall(groot, 'Type', 'figure'), figBefore);
decompFig = pickFigureByName(decompFigCandidates, 'AFM');
if isempty(decompFig)
    if isempty(decompFigCandidates)
        error('No decomposition figure was generated by plotDecompositionExamples.');
    end
    decompFig = decompFigCandidates(1);
end

% ---------------- Combine existing generated figures ----------------
[hCombined, combineInfo] = combineFiguresFromExisting(deltaFig, decompFig);
addCanonicalAnnotation(hCombined);

savefig(hCombined, figOutFig);
exportgraphics(hCombined, figOutPng, 'Resolution', 300);

% ---------------- Report ----------------
fieldUsage = inspectFieldUsage(state.pauseRuns);
defs = resolveDefinitionReferences(repoRoot);
writeReport(reportOut, plotSources, fieldUsage, defs, dataLog, combineInfo, ...
    figOutFig, figOutPng);

fprintf('Saved: %s\n', figOutFig);
fprintf('Saved: %s\n', figOutPng);
fprintf('Saved: %s\n', reportOut);

% =====================================================================
function plotSources = discoverPlotSources(repoRoot)
plotSources = struct();

plotSources.scopeScan = {
    fullfile(repoRoot, 'Aging', 'analyzeAgingMemory.m')
    fullfile(repoRoot, 'Aging', 'pipeline', 'stage4_analyzeAFM_FM.m')
    fullfile(repoRoot, 'Aging', 'models', 'analyzeAFM_FM_components.m')
    };

plotSources.stage4_call_debugPlotGeometry.file = fullfile(repoRoot, 'Aging', 'pipeline', 'stage4_analyzeAFM_FM.m');
plotSources.stage4_call_debugPlotGeometry.line = findLineContains(plotSources.stage4_call_debugPlotGeometry.file, 'debugPlotGeometry(state, cfg)');
plotSources.stage4_call_debugPlotGeometry.call = 'debugPlotGeometry(state, cfg)';
plotSources.stage4_call_debugPlotGeometry.resolved = which('debugPlotGeometry');

plotSources.stage4_call_plotDecompositionExamples.file = fullfile(repoRoot, 'Aging', 'pipeline', 'stage4_analyzeAFM_FM.m');
plotSources.stage4_call_plotDecompositionExamples.line = findLineContains(plotSources.stage4_call_plotDecompositionExamples.file, 'plotDecompositionExamples(state, cfg)');
plotSources.stage4_call_plotDecompositionExamples.call = 'plotDecompositionExamples(state, cfg)';
plotSources.stage4_call_plotDecompositionExamples.resolved = which('plotDecompositionExamples');

plotSources.stage8_call_plotAgingMemory.file = fullfile(repoRoot, 'Aging', 'pipeline', 'stage8_plotting.m');
plotSources.stage8_call_plotAgingMemory.line = findLineContains(plotSources.stage8_call_plotAgingMemory.file, 'plotAgingMemory(state.noPause_T, state.noPause_M, state.pauseRuns, cfg.color_scheme, ...');
plotSources.stage8_call_plotAgingMemory.call = ['plotAgingMemory(state.noPause_T, state.noPause_M, state.pauseRuns, cfg.color_scheme, ' ...
    'cfg.fontsize, cfg.linewidth, cfg.sample_name, cfg.Bohar_units, cfg.offsetMode, cfg.offsetValue, cfg.dip_window_K, cfg.colorRange, cfg.useAutoYScale)'];
plotSources.stage8_call_plotAgingMemory.resolved = which('plotAgingMemory');

plotSources.decomp_bridge.file = fullfile(repoRoot, 'Aging', 'analysis', 'plotDecompositionExamples.m');
plotSources.decomp_bridge.line = findLineContains(plotSources.decomp_bridge.file, 'plotAFM_FM_decomposition(state.pauseRuns(idx));');
plotSources.decomp_bridge.call = 'plotAFM_FM_decomposition(state.pauseRuns(idx))';
plotSources.decomp_bridge.resolved = which('plotAFM_FM_decomposition');
end

function [state, cfg, dataLog] = loadOrBuildState(repoRoot)
cfg = struct();
dataLog = struct();
dataLog.mode = '';
dataLog.notes = {};

try
    cfg = agingConfig();
catch ME
    dataLog.notes{end+1} = sprintf('agingConfig failed: %s', ME.message);
end

cfg = ensureCfgDefaults(cfg);

% Try real pipeline data first (same structs as pipeline stages).
try
    cfg = stage0_setupPaths(cfg);
    state = stage1_loadData(cfg);
    state = stage2_preprocess(state, cfg);
    state = stage3_computeDeltaM(state, cfg);
    state = stage4_analyzeAFM_FM(state, cfg);
    dataLog.mode = 'pipeline_stages_1_to_4';
    dataLog.notes{end+1} = sprintf('dataDir=%s', cfg.dataDir);
    return;
catch ME
    dataLog.notes{end+1} = sprintf('Pipeline stage build failed: %s', ME.message);
end

% Try real pipeline data by discovering dataDir from existing debug metrics.
try
    [cfg2, sourceMat] = cfgFromDebugMetricsSource(repoRoot, cfg);
    state = stage1_loadData(cfg2);
    state = stage2_preprocess(state, cfg2);
    state = stage3_computeDeltaM(state, cfg2);
    state = stage4_analyzeAFM_FM(state, cfg2);
    cfg = cfg2;
    dataLog.mode = 'pipeline_stages_1_to_4_from_debug_sourceFile';
    dataLog.notes{end+1} = sprintf('dataDir=%s', cfg.dataDir);
    dataLog.notes{end+1} = sprintf('debugMetricsMat=%s', sourceMat);
    return;
catch ME
    dataLog.notes{end+1} = sprintf('Debug-metrics derived build failed: %s', ME.message);
end

% Fallback: load latest saved state-like MAT artifact.
[state, matPath] = loadLatestStateSnapshot(repoRoot);
cfg = ensurePlotConfig(cfg, state);
if ~isfield(cfg, 'dataDir') || isempty(cfg.dataDir)
    cfg.dataDir = fileparts(matPath);
end
dataLog.mode = 'loaded_mat_snapshot';
dataLog.notes{end+1} = sprintf('loaded=%s', matPath);
end

function [state, matPath] = loadLatestStateSnapshot(repoRoot)
roots = {
    fullfile(repoRoot, 'results')
    fullfile(repoRoot, 'runs')
    fullfile(repoRoot, 'results_old')
    fullfile(repoRoot, 'Aging', 'results')
    };

allFiles = [];
for i = 1:numel(roots)
    if exist(roots{i}, 'dir')
        d = dir(fullfile(roots{i}, '**', '*.mat'));
        if ~isempty(d)
            allFiles = [allFiles; d(:)]; %#ok<AGROW>
        end
    end
end

if isempty(allFiles)
    error('No MAT files found for fallback state loading.');
end

[~, idxSort] = sort([allFiles.datenum], 'descend');
allFiles = allFiles(idxSort);

for i = 1:numel(allFiles)
    matPath = fullfile(allFiles(i).folder, allFiles(i).name);
    try
        vars = whos('-file', matPath);
        names = {vars.name};
        if any(strcmp(names, 'state'))
            S = load(matPath, 'state');
            if isStateLike(S.state)
                state = S.state;
                return;
            end
        end

        hasPauseRuns = any(strcmp(names, 'pauseRuns'));
        hasNoPauseT = any(strcmp(names, 'noPause_T'));
        hasNoPauseM = any(strcmp(names, 'noPause_M'));
        if hasPauseRuns && hasNoPauseT && hasNoPauseM
            S = load(matPath, 'pauseRuns', 'noPause_T', 'noPause_M');
            state = struct();
            state.pauseRuns = S.pauseRuns;
            state.noPause_T = S.noPause_T;
            state.noPause_M = S.noPause_M;
            return;
        end
    catch
        % Continue scanning.
    end
end

error('No state-like MAT snapshot was found in fallback directories.');
end

function [cfgOut, sourceMat] = cfgFromDebugMetricsSource(repoRoot, cfgIn)
cfgOut = ensureCfgDefaults(cfgIn);
sourceMat = '';

roots = {
    fullfile(repoRoot, 'results', 'aging')
    fullfile(repoRoot, 'results_old', 'aging')
    };

matFiles = [];
for i = 1:numel(roots)
    if exist(roots{i}, 'dir')
        d = dir(fullfile(roots{i}, '**', 'debug_metrics.mat'));
        if ~isempty(d)
            matFiles = [matFiles; d(:)];
        end
    end
end

if isempty(matFiles)
    error('No debug_metrics.mat files were found for dataDir discovery.');
end

[~, ord] = sort([matFiles.datenum], 'descend');
matFiles = matFiles(ord);

for i = 1:numel(matFiles)
    sourceMat = fullfile(matFiles(i).folder, matFiles(i).name);
    try
        S = load(sourceMat, 'debugTable');
        if ~isfield(S, 'debugTable') || isempty(S.debugTable)
            continue;
        end
        if ~ismember('sourceFile', S.debugTable.Properties.VariableNames)
            continue;
        end
        sourceFile = string(S.debugTable.sourceFile(1));
        if strlength(sourceFile) == 0
            continue;
        end
        sourceFile = char(sourceFile);
        dataDir = fileparts(sourceFile);
        if ~exist(dataDir, 'dir')
            continue;
        end
        cfgOut.dataDir = dataDir;
        cfgOut = stage0_setupPaths(cfgOut);
        return;
    catch
        % Continue scanning.
    end
end

error('Could not derive a valid dataDir from any debug_metrics.mat sourceFile.');
end

function tf = isStateLike(state)
tf = isstruct(state) && isfield(state, 'pauseRuns') && isfield(state, 'noPause_T') && isfield(state, 'noPause_M');
end

function cfg = ensureCfgDefaults(cfg)
if nargin < 1 || ~isstruct(cfg), cfg = struct(); end
cfg = setDefault(cfg, 'normalizeByMass', true);
cfg = setDefault(cfg, 'debugMode', true);
cfg = setDefault(cfg, 'color_scheme', 'thermal');
cfg = setDefault(cfg, 'fontsize', 20);
cfg = setDefault(cfg, 'linewidth', 2.0);
cfg = setDefault(cfg, 'sample_name', 'Aging Sample');
cfg = setDefault(cfg, 'Bohar_units', true);
cfg = setDefault(cfg, 'offsetMode', 'none');
cfg = setDefault(cfg, 'offsetValue', 120);
cfg = setDefault(cfg, 'dip_window_K', 5);
if ~isfield(cfg, 'smoothWindow_K') || isempty(cfg.smoothWindow_K)
    cfg.smoothWindow_K = 4 * cfg.dip_window_K;
end
cfg = setDefault(cfg, 'colorRange', [0 1]);
cfg = setDefault(cfg, 'useAutoYScale', true);
cfg = setDefault(cfg, 'showAllPauses_AFmFM', false);
cfg = setDefault(cfg, 'examplePause_K', []);
cfg = setDefault(cfg, 'doPlotting', false);
cfg = setDefault(cfg, 'showAFM_FM_example', false);
cfg = setDefault(cfg, 'excludeLowT_FM', true);
cfg = setDefault(cfg, 'excludeLowT_K', 6);
cfg = setDefault(cfg, 'FM_plateau_K', 6);
cfg = setDefault(cfg, 'excludeLowT_mode', 'pre');
cfg = setDefault(cfg, 'FM_buffer_K', 6);
cfg = setDefault(cfg, 'AFM_metric_main', 'area');
cfg = setDefault(cfg, 'agingMetricMode', 'direct');
cfg = setDefault(cfg, 'FMConvention', 'leftMinusRight');
cfg = setDefault(cfg, 'subtractOrder', 'pauseMinusNo');
cfg = setDefault(cfg, 'alignDeltaM', false);
cfg = setDefault(cfg, 'alignRef', 'lowT');
cfg = setDefault(cfg, 'alignWindow_K', 2);
cfg = setDefault(cfg, 'doFilterDeltaM', true);
cfg = setDefault(cfg, 'filterMethod', 'sgolay');
cfg = setDefault(cfg, 'sgolayOrder', 2);
cfg = setDefault(cfg, 'sgolayFrame', 15);
end

function cfg = ensurePlotConfig(cfg, state)
cfg = ensureCfgDefaults(cfg);
if (~isfield(cfg, 'sample_name') || isempty(cfg.sample_name)) && isfield(state, 'sample_name')
    cfg.sample_name = state.sample_name;
end
if ~isfield(cfg, 'examplePause_K') || isempty(cfg.examplePause_K)
    cfg.examplePause_K = pickExamplePauseK(state.pauseRuns);
end
end

function tf = hasDecompositionFields(pauseRuns)
if isempty(pauseRuns)
    tf = false;
    return;
end
req = {'DeltaM_smooth', 'DeltaM_sharp'};
tf = true;
for i = 1:numel(req)
    if ~isfield(pauseRuns, req{i})
        tf = false;
        return;
    end
end
end

function Tp = pickExamplePauseK(pauseRuns)
Tp = NaN;
if isempty(pauseRuns) || ~isfield(pauseRuns, 'waitK')
    return;
end
vals = [pauseRuns.waitK];
vals = vals(isfinite(vals));
if isempty(vals)
    return;
end
Tp = vals(1);
end

function hFig = pickDeltaFigure(figCandidates)
hFig = [];
if isempty(figCandidates), return; end
for i = 1:numel(figCandidates)
    ax = findall(figCandidates(i), 'Type', 'axes');
    for j = 1:numel(ax)
        ylbl = getLabelText(get(ax(j), 'YLabel'));
        ttl = getTitleText(ax(j));
        if contains(lower(ylbl), 'delta') || contains(lower(ttl), 'delta') || ...
                contains(ylbl, '\Delta') || contains(ttl, '\Delta')
            hFig = figCandidates(i);
            return;
        end
    end
end
% Fallback: last created figure in this batch.
hFig = figCandidates(1);
end

function hFig = pickFigureByName(figCandidates, token)
hFig = [];
if isempty(figCandidates), return; end
for i = 1:numel(figCandidates)
    nm = string(get(figCandidates(i), 'Name'));
    if contains(lower(nm), lower(token))
        hFig = figCandidates(i);
        return;
    end
end
end

function [hCombined, combineInfo] = combineFiguresFromExisting(deltaFig, decompFig)
deltaAxes = getOrderedAxes(deltaFig);
decompAxes = getOrderedAxes(decompFig);
allAxes = [deltaAxes(:); decompAxes(:)];

if isempty(allAxes)
    error('No axes were found in source figures to combine.');
end

hCombined = figure('Color', 'w', 'Name', 'Aging Existing Pipeline Decomposition (Annotated)');
tl = tiledlayout(numel(allAxes), 1, 'TileSpacing', 'compact', 'Padding', 'compact'); %#ok<NASGU>

for i = 1:numel(allAxes)
    axDst = nexttile;
    cloneAxesContent(allAxes(i), axDst);
end

sgtitle('Existing Pipeline Plots (Reused) + Canonical Annotation');

combineInfo = struct();
combineInfo.n_axes_delta = numel(deltaAxes);
combineInfo.n_axes_decomp = numel(decompAxes);
combineInfo.n_axes_total = numel(allAxes);
end

function addCanonicalAnnotation(hFig)
txt = sprintf([ ...
    'Definitions:\\n' ...
    'DeltaM = M_pause - M_noPause  (canonical definition)\\n' ...
    'FM = baseL - baseR            (signed background / step)\\n' ...
    'dip = DeltaM - DeltaM_smooth  (residual / AFM component)\\n\\n' ...
    'Notes:\\n' ...
    '- This figure is generated using EXISTING pipeline plotting functions\\n' ...
    '- This is a PRE-CANONICAL visualization artifact\\n' ...
    '- Some quantities may still depend on legacy/non-canonical extraction paths\\n' ...
    '- Metric-based quantities (e.g. window dip, tau_dip) are NOT physical observables']);

annotation(hFig, 'textbox', [0.50 0.01 0.49 0.20], ...
    'String', txt, ...
    'Interpreter', 'none', ...
    'EdgeColor', [0.3 0.3 0.3], ...
    'BackgroundColor', [1 1 1], ...
    'FontSize', 10);
end

function fieldUsage = inspectFieldUsage(pauseRuns)
fieldUsage = struct();
n = numel(pauseRuns);
fieldUsage.n_runs = n;
fieldUsage.has_DeltaM_signed = countFieldNonEmpty(pauseRuns, 'DeltaM_signed');
fieldUsage.has_FM_signed = countFieldFiniteScalar(pauseRuns, 'FM_signed');
fieldUsage.has_dip_signed = countFieldNonEmpty(pauseRuns, 'dip_signed');
fieldUsage.has_DeltaM = countFieldNonEmpty(pauseRuns, 'DeltaM');
fieldUsage.has_FM_step_raw = countFieldFiniteScalar(pauseRuns, 'FM_step_raw');
fieldUsage.has_DeltaM_sharp = countFieldNonEmpty(pauseRuns, 'DeltaM_sharp');

if fieldUsage.has_DeltaM_signed > 0
    fieldUsage.deltam_source = 'DeltaM_signed (canonical when available)';
else
    fieldUsage.deltam_source = 'fallback: DeltaM (legacy observable)';
end

if fieldUsage.has_FM_signed > 0
    fieldUsage.fm_source = 'FM_signed';
elseif fieldUsage.has_FM_step_raw > 0
    fieldUsage.fm_source = 'fallback: FM_step_raw';
else
    fieldUsage.fm_source = 'fallback: FM_step_mag or missing';
end

if fieldUsage.has_dip_signed > 0
    fieldUsage.dip_source = 'dip_signed';
elseif fieldUsage.has_DeltaM_sharp > 0
    fieldUsage.dip_source = 'fallback: DeltaM_sharp';
else
    fieldUsage.dip_source = 'fallback: unavailable';
end
end

function defs = resolveDefinitionReferences(repoRoot)
defs = struct();

defs.delta.file = fullfile(repoRoot, 'Aging', 'analyzeAgingMemory.m');
defs.delta.expr = 'canonicalDeltaM = M_pa_i - M_no_i;';
defs.delta.line = findLineContains(defs.delta.file, defs.delta.expr);

defs.fm.file = fullfile(repoRoot, 'Aging', 'models', 'analyzeAFM_FM_components.m');
defs.fm.expr = 'fmValue = baseL - baseR;';
defs.fm.line = findLineContains(defs.fm.file, defs.fm.expr);

defs.dip.file = fullfile(repoRoot, 'Aging', 'models', 'analyzeAFM_FM_components.m');
defs.dip.expr = 'dip_signed = DeltaM_signed - dM_smooth;';
defs.dip.line = findLineContains(defs.dip.file, defs.dip.expr);
end

function writeReport(reportPath, plotSources, fieldUsage, defs, dataLog, combineInfo, figOutFig, figOutPng)
fid = fopen(reportPath, 'w');
if fid < 0
    error('Could not open report file for writing: %s', reportPath);
end
cleanupObj = onCleanup(@() fclose(fid));

fprintf(fid, '# Aging DeltaM Decomposition Using Existing Pipeline Plots\n\n');

fprintf(fid, '## 1. Plot Sources\n\n');
fprintf(fid, '- Scope files scanned:\n');
for i = 1:numel(plotSources.scopeScan)
    fprintf(fid, '  - `%s`\n', toRel(plotSources.scopeScan{i}));
end
fprintf(fid, '\n');
fprintf(fid, '- Stage4 delegated plot call: `%s` (`%s:%d`)\n', ...
    plotSources.stage4_call_plotDecompositionExamples.call, ...
    toRel(plotSources.stage4_call_plotDecompositionExamples.file), ...
    plotSources.stage4_call_plotDecompositionExamples.line);
fprintf(fid, '- Stage4 geometry debug plot call: `%s` (`%s:%d`)\n', ...
    plotSources.stage4_call_debugPlotGeometry.call, ...
    toRel(plotSources.stage4_call_debugPlotGeometry.file), ...
    plotSources.stage4_call_debugPlotGeometry.line);
fprintf(fid, '- Pipeline DeltaM figure call (stage8): `%s` (`%s:%d`)\n', ...
    plotSources.stage8_call_plotAgingMemory.call, ...
    toRel(plotSources.stage8_call_plotAgingMemory.file), ...
    plotSources.stage8_call_plotAgingMemory.line);
fprintf(fid, '- Decomposition bridge call: `%s` (`%s:%d`)\n', ...
    plotSources.decomp_bridge.call, ...
    toRel(plotSources.decomp_bridge.file), ...
    plotSources.decomp_bridge.line);
fprintf(fid, '\n');
fprintf(fid, '- Resolved function files actually reused:\n');
fprintf(fid, '  - `plotAgingMemory`: `%s`\n', toRel(plotSources.stage8_call_plotAgingMemory.resolved));
fprintf(fid, '  - `plotDecompositionExamples`: `%s`\n', toRel(plotSources.stage4_call_plotDecompositionExamples.resolved));
fprintf(fid, '  - `plotAFM_FM_decomposition`: `%s`\n', toRel(plotSources.decomp_bridge.resolved));
fprintf(fid, '\n');

fprintf(fid, '## 2. Field Usage\n\n');
fprintf(fid, '- Data source mode: `%s`\n', dataLog.mode);
for i = 1:numel(dataLog.notes)
    fprintf(fid, '- Note: %s\n', dataLog.notes{i});
end
fprintf(fid, '\n');
fprintf(fid, '- Runs analyzed: `%d`\n', fieldUsage.n_runs);
fprintf(fid, '- DeltaM_signed present in `%d/%d` runs\n', fieldUsage.has_DeltaM_signed, fieldUsage.n_runs);
fprintf(fid, '- FM_signed present in `%d/%d` runs\n', fieldUsage.has_FM_signed, fieldUsage.n_runs);
fprintf(fid, '- dip_signed present in `%d/%d` runs\n', fieldUsage.has_dip_signed, fieldUsage.n_runs);
fprintf(fid, '- DeltaM source used: `%s`\n', fieldUsage.deltam_source);
fprintf(fid, '- FM source used: `%s`\n', fieldUsage.fm_source);
fprintf(fid, '- dip source used: `%s`\n', fieldUsage.dip_source);
fprintf(fid, '\n');

fprintf(fid, '## 3. Explicit Definitions\n\n');
fprintf(fid, '- DeltaM:\n');
fprintf(fid, '  - Code expression: `%s`\n', defs.delta.expr);
fprintf(fid, '  - Source: `%s:%d`\n', toRel(defs.delta.file), defs.delta.line);
fprintf(fid, '\n');
fprintf(fid, '- FM:\n');
fprintf(fid, '  - Code expression: `%s`\n', defs.fm.expr);
fprintf(fid, '  - Source: `%s:%d`\n', toRel(defs.fm.file), defs.fm.line);
fprintf(fid, '\n');
fprintf(fid, '- dip:\n');
fprintf(fid, '  - Code expression: `%s`\n', defs.dip.expr);
fprintf(fid, '  - Source: `%s:%d`\n', toRel(defs.dip.file), defs.dip.line);
fprintf(fid, '\n');

fprintf(fid, '## 4. Classification\n\n');
fprintf(fid, '- DeltaM -> canonical observable\n');
fprintf(fid, '- FM -> signed physical component\n');
fprintf(fid, '- dip -> canonical residual\n');
fprintf(fid, '- window dip / tau_dip -> NON-CANONICAL metrics\n\n');

fprintf(fid, '## 5. Combined Figure Build\n\n');
fprintf(fid, '- Combined axes copied from existing figures: `%d` total (`%d` DeltaM + `%d` decomposition)\n', ...
    combineInfo.n_axes_total, combineInfo.n_axes_delta, combineInfo.n_axes_decomp);
fprintf(fid, '- Saved figure (FIG): `%s`\n', toRel(figOutFig));
fprintf(fid, '- Saved figure (PNG): `%s`\n', toRel(figOutPng));
fprintf(fid, '\n');

fprintf(fid, '## 6. Warning\n\n');
fprintf(fid, '> This artifact reflects the current state of the aging pipeline BEFORE full canonicalization.\n');
end

function n = countFieldNonEmpty(s, fieldName)
n = 0;
for i = 1:numel(s)
    if isfield(s(i), fieldName) && ~isempty(s(i).(fieldName))
        n = n + 1;
    end
end
end

function n = countFieldFiniteScalar(s, fieldName)
n = 0;
for i = 1:numel(s)
    if isfield(s(i), fieldName) && ~isempty(s(i).(fieldName))
        v = s(i).(fieldName);
        if isnumeric(v) && isscalar(v) && isfinite(v)
            n = n + 1;
        end
    end
end
end

function idx = findLineContains(filePath, token)
idx = NaN;
if ~exist(filePath, 'file')
    return;
end
c = readlines(filePath);
for i = 1:numel(c)
    if contains(c(i), token)
        idx = i;
        return;
    end
end
end

function axOut = getOrderedAxes(hFig)
ax = findall(hFig, 'Type', 'axes');
if isempty(ax)
    axOut = gobjects(0);
    return;
end

keep = false(size(ax));
for i = 1:numel(ax)
    keep(i) = ~isempty(allchild(ax(i)));
end
if any(keep)
    ax = ax(keep);
end

pos = zeros(numel(ax), 4);
for i = 1:numel(ax)
    pos(i, :) = get(ax(i), 'Position');
end
[~, ord] = sortrows([-pos(:,2), pos(:,1)]);
axOut = ax(ord);
end

function cloneAxesContent(srcAx, dstAx)
copyobj(allchild(srcAx), dstAx);
set(dstAx, 'XLim', get(srcAx, 'XLim'));
set(dstAx, 'YLim', get(srcAx, 'YLim'));
set(dstAx, 'XScale', get(srcAx, 'XScale'));
set(dstAx, 'YScale', get(srcAx, 'YScale'));
grid(dstAx, get(srcAx, 'XGrid'));
box(dstAx, get(srcAx, 'Box'));

xlabel(dstAx, getLabelText(get(srcAx, 'XLabel')), 'Interpreter', 'none');
ylabel(dstAx, getLabelText(get(srcAx, 'YLabel')), 'Interpreter', 'none');
title(dstAx, getTitleText(srcAx), 'Interpreter', 'none');
end

function txt = getLabelText(hLabel)
txt = '';
if isempty(hLabel) || ~isgraphics(hLabel), return; end
v = get(hLabel, 'String');
txt = toText(v);
end

function txt = getTitleText(hAx)
txt = '';
if isempty(hAx) || ~isgraphics(hAx), return; end
hTitle = get(hAx, 'Title');
if isempty(hTitle) || ~isgraphics(hTitle), return; end
txt = toText(get(hTitle, 'String'));
end

function txt = toText(v)
if isstring(v)
    txt = char(join(v, ' '));
elseif iscell(v)
    try
        txt = strjoin(cellfun(@char, v, 'UniformOutput', false), ' ');
    catch
        txt = '';
    end
elseif ischar(v)
    txt = v;
else
    txt = '';
end
end

function out = toRel(pathIn)
if isempty(pathIn)
    out = '';
    return;
end
root = fileparts(fileparts(mfilename('fullpath')));
p = char(pathIn);
out = strrep(p, [root filesep], '');
end
