clear; clc;

repoRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(fullfile(repoRoot, 'tools'));
addpath(fullfile(repoRoot, 'Aging', 'utils'));
addpath(fullfile(repoRoot, 'Switching', 'utils'));

runDir = '';
baseName = 'switching_backbone_selection_adjudication_plan';

% Required plan status flags
fPlanDefined = 'YES';
fSelectionReady = 'PARTIAL';
fCurrentPhysicalLocked = 'NO';
fCurrentOperationalRef = 'YES';
fRmseOnlyAllowed = 'NO';
fPhi1Required = 'YES';
fLegacyWidthTruthAllowed = 'NO';
fCandidateSetDefined = 'YES';
fDecisionRulesDefined = 'YES';
fReadyForRun = 'PARTIAL';

try
    cfg = struct();
    cfg.runLabel = baseName;
    cfg.dataset = 'backbone_selection_plan';
    cfg.fingerprint_script_path = fullfile(fileparts(mfilename('fullpath')), [mfilename '.m']);
    run = createSwitchingRunContext(repoRoot, cfg);
    runDir = run.run_dir;
    runTables = fullfile(runDir, 'tables');
    runReports = fullfile(runDir, 'reports');
    if exist(runTables, 'dir') ~= 7, mkdir(runTables); end
    if exist(runReports, 'dir') ~= 7, mkdir(runReports); end
    if exist(fullfile(repoRoot, 'tables'), 'dir') ~= 7, mkdir(fullfile(repoRoot, 'tables')); end
    if exist(fullfile(repoRoot, 'reports'), 'dir') ~= 7, mkdir(fullfile(repoRoot, 'reports')); end

    writeSwitchingExecutionStatus(runDir, {'PARTIAL'}, {'YES'}, {''}, 0, {'selection plan initialized'}, false);

    % Context references (read-only, no new analyses)
    pB = fullfile(repoRoot, 'tables', 'switching_backbone_validity_status.csv');
    pC = fullfile(repoRoot, 'tables', 'switching_mode_admissibility_status.csv');
    pB0 = fullfile(repoRoot, 'tables', 'switching_decomposition_foundation_status.csv');
    pAdj = fullfile(repoRoot, 'tables', 'switching_backbone_adjudication_pilot_status.csv');
    pIdentity = fullfile(repoRoot, 'tables', 'switching_canonical_identity.csv');
    refs = {pB,pC,pB0,pAdj,pIdentity};
    for i = 1:numel(refs)
        if exist(refs{i}, 'file') ~= 2
            error('run_switching_backbone_selection_adjudication_plan:MissingInput', ...
                'Missing context table: %s', refs{i});
        end
    end

    % 1) Candidate family set
    cand = [ ...
        "current_ptcdf_reference"; ...
        "current_ptcdf_with_tail_controls_only"; ...
        "derivative_first_ptcdf"; ...
        "amplitude_normalized_mean_shape"; ...
        "residual_pca_no_pt_reference"; ...
        "quantile_coordinate_ptcdf"; ...
        "two_sector_ptcdf_tail_aware_constrained"; ...
        "tail_aware_ptcdf_correction_fixed_threshold"];
    allowedInputs = [ ...
        "canonical S_long + canonical phi1 + mode amplitudes"; ...
        "canonical S_long + canonical phi1 + mode amplitudes + canonical diagnostics"; ...
        "canonical S_long only (+ canonical diagnostics for checks)"; ...
        "canonical S_long only (+ canonical diagnostics for checks)"; ...
        "canonical S_long only (+ canonical diagnostics for checks)"; ...
        "canonical S_long only (+ canonical diagnostics for checks)"; ...
        "canonical S_long + canonical phi1 + mode amplitudes"; ...
        "canonical S_long + canonical phi1 + mode amplitudes"];
    forbiddenInputs = [ ...
        "legacy width/shift/alignment outputs; stress outputs as truth"; ...
        "legacy width/shift/alignment outputs; stress outputs as truth"; ...
        "legacy width/shift/alignment outputs; stress outputs as truth"; ...
        "legacy width/shift/alignment outputs; stress outputs as truth"; ...
        "legacy width/shift/alignment outputs; stress outputs as truth"; ...
        "legacy width/shift/alignment outputs; stress outputs as truth"; ...
        "legacy width/shift/alignment outputs; stress outputs as truth"; ...
        "legacy width/shift/alignment outputs; stress outputs as truth"];
    noncanonicalEvidenceUsed = [ ...
        "NO"; "NO"; "PARTIAL"; "PARTIAL"; "PARTIAL"; "NO"; "PARTIAL"; "PARTIAL"];
    physicallyInterp = [ ...
        "YES"; "YES"; "PARTIAL"; "PARTIAL"; "NO"; "PARTIAL"; "YES"; "PARTIAL"];
    hiddenFreedomRisk = [ ...
        "LOW"; "LOW"; "MEDIUM"; "HIGH"; "HIGH"; "HIGH"; "MEDIUM"; "MEDIUM"];
    absorbPhi1Risk = [ ...
        "LOW"; "LOW"; "MEDIUM"; "HIGH"; "HIGH"; "HIGH"; "MEDIUM"; "MEDIUM"];
    absorbPhi2Risk = [ ...
        "LOW"; "LOW"; "MEDIUM"; "HIGH"; "HIGH"; "HIGH"; "HIGH"; "HIGH"];
    tailEffect = [ ...
        "baseline"; "analysis-side mitigation only"; "low-to-medium reduction"; "potential reduction but high mode-mixing risk"; ...
        "can reduce but nonphysical decomposition risk"; "unknown-to-medium"; "high reduction potential"; "high reduction potential"];
    pilotEligible = [ ...
        "NO"; "NO"; "YES"; "YES"; "YES"; "PARTIAL"; "YES"; "YES"];
    canonicalEligibleLater = [ ...
        "YES"; "YES"; "PARTIAL"; "PARTIAL"; "NO"; "PARTIAL"; "YES"; "PARTIAL"];
    notes = [ ...
        "Operational reference backbone."; ...
        "No backbone replacement; tail controls in interpretation only."; ...
        "Must prove no hidden coordinate flexibility."; ...
        "Strong risk of absorbing Phi1/2 without constraints."; ...
        "Diagnostic baseline only; likely nonphysical as backbone truth."; ...
        "Potentially interpretable but currently underconstrained."; ...
        "Current recommended pilot candidate; PILOT_ONLY until gates pass."; ...
        "Must keep threshold fixed and predeclared; no per-T tuning."];

    famTbl = table(cand, allowedInputs, forbiddenInputs, noncanonicalEvidenceUsed, physicallyInterp, ...
        hiddenFreedomRisk, absorbPhi1Risk, absorbPhi2Risk, tailEffect, pilotEligible, canonicalEligibleLater, notes, ...
        'VariableNames', {'candidate_family','allowed_inputs','forbidden_inputs', ...
        'uses_noncanonical_diagnostic_evidence','physically_interpretable','risk_hidden_width_shift_alignment_freedom', ...
        'risk_absorbing_phi1','risk_absorbing_phi2','expected_high_cdf_tail_effect', ...
        'allowed_as_noncanonical_pilot','eligible_for_future_canonical_redesign_after_gates','notes'});
    switchingWriteTableBothPaths(famTbl, repoRoot, runTables, 'switching_backbone_selection_candidate_families.csv');

    % 2) Admissibility hard gates
    gate = [ ...
        "NO_WIDTH_SCALING"; ...
        "NO_LEGACY_ALIGNMENT"; ...
        "NO_PER_T_ARBITRARY_SHIFT_SCALE"; ...
        "NO_PHI2_FITTED_BACKBONE_COMPONENT"; ...
        "NO_STRESS_OUTPUT_AS_TRAINING_TRUTH"; ...
        "NO_CANONICAL_IDENTITY_OR_TRUTH_OUTPUT_CHANGE"; ...
        "PHI1_PRESERVATION_REQUIRED"; ...
        "RESIDUAL_SPECTRUM_INTERPRETABLE"; ...
        "NO_RMSE_ONLY_SELECTION"; ...
        "OUTPUTS_DIAGNOSTIC_UNLESS_CANONIZED_LATER"];
    gateType = [ ...
        "hard_fail"; "hard_fail"; "hard_fail"; "hard_fail"; "hard_fail"; "hard_fail"; ...
        "hard_fail"; "hard_fail"; "hard_fail"; "hard_fail"];
    gateCheck = [ ...
        "verify coordinate definition excludes width normalization"; ...
        "verify no shift/scale alignment artifacts used"; ...
        "audit absence of per-T free shift/scale parameters"; ...
        "inspect backbone formula terms for Phi2 usage"; ...
        "ensure stress tables are comparison-only metadata"; ...
        "diff identity/canonical outputs before/after run"; ...
        "require Phi1 cosine + amplitude preservation thresholds"; ...
        "require stable mode ordering and bounded mode-energy drift"; ...
        "fail if RMSE gain without tail + Phi1 + spectrum improvement"; ...
        "require NON_CANONICAL_DIAGNOSTIC labeling unless explicit canonization stage"];
    gateTbl = table(gate, gateType, gateCheck, ...
        'VariableNames', {'admissibility_gate','gate_type','verification_method'});
    switchingWriteTableBothPaths(gateTbl, repoRoot, runTables, 'switching_backbone_selection_admissibility_gates.csv');

    % 3) Quantitative metrics plan
    mName = [ ...
        "backbone_only_rmse"; ...
        "high_cdf_tail_burden_ratio"; ...
        "residual_energy_by_cdf_windows"; ...
        "residual_svd_spectrum"; ...
        "phi1_cosine_preservation"; ...
        "phi1_amplitude_stability"; ...
        "phi1_absorption_test"; ...
        "phi2_absorption_or_clarification_test"; ...
        "cdf_monotonicity_pt_pdf_validity"; ...
        "complexity_dof_penalty"; ...
        "subset_robustness_highT_transition_boundary"];
    mDefinition = [ ...
        "RMSE(S - backbone) against canonical measured S"; ...
        "high-CDF/mid-CDF residual-energy ratio and reduction"; ...
        "low/mid/high CDF residual fractions"; ...
        "mode energy fractions and ordering stability"; ...
        "|cos(Phi1_candidate, Phi1_canonical)|"; ...
        "relative change in Phi1-projected amplitude proxy"; ...
        "detect if Phi1 is suppressed/hidden by backbone freedom"; ...
        "assess whether Phi2 remains residual and interpretable"; ...
        "if candidate defines PT/CDF-like coordinate, verify validity"; ...
        "penalize additional free parameters and hidden flexibility"; ...
        "recompute excluding high-T, 22-24K, boundary bins"];
    mThreshold = [ ...
        "improvement required but not sufficient alone"; ...
        "must improve for redesign candidacy"; ...
        "must not worsen while claiming tail fix"; ...
        "must remain interpretable"; ...
        ">=0.90 baseline gate"; ...
        "<=15% median shift baseline gate"; ...
        "must be NO for admissible redesign candidate"; ...
        "must show clarification, not backbone absorption"; ...
        "must remain valid if coordinate is used"; ...
        "lower complexity preferred when performance comparable"; ...
        "must remain consistent across required subsets"];
    mPlanTbl = table(mName, mDefinition, mThreshold, ...
        'VariableNames', {'metric','definition','selection_threshold_or_expectation'});
    switchingWriteTableBothPaths(mPlanTbl, repoRoot, runTables, 'switching_backbone_selection_metrics_plan.csv');

    % 4) Decision rules
    ruleName = [ ...
        "CURRENT_ACCEPTED"; ...
        "REDESIGN_REQUIRED"; ...
        "INCONCLUSIVE"; ...
        "REOPEN_DECOMPOSITION"];
    trigger = [ ...
        "No admissible candidate beats current after hard gates + penalties"; ...
        "At least one candidate passes all hard gates, preserves Phi1, improves tail and RMSE, reduces ambiguity"; ...
        "Mixed outcomes: partial improvements but key hard gate failures"; ...
        "Multiple admissible families imply conflicting residual-mode interpretations"];
    consequence = [ ...
        "Keep current PT/CDF as controlling backbone; allow mechanism interpretation with existing caveats"; ...
        "Enter controlled canonical redesign track (not automatic replacement)"; ...
        "Block mechanism interpretation broad claims; require additional adjudication rounds"; ...
        "Pause mechanism interpretation and reopen decomposition architecture design"];
    decisionTbl = table(ruleName, trigger, consequence, ...
        'VariableNames', {'decision_rule','trigger_condition','required_action'});
    switchingWriteTableBothPaths(decisionTbl, repoRoot, runTables, 'switching_backbone_selection_decision_rules.csv');

    % 5) Plan status flags
    statusTbl = table( ...
        ["BACKBONE_SELECTION_PLAN_DEFINED"; ...
         "BACKBONE_SELECTION_READY_TO_RUN"; ...
         "CURRENT_BACKBONE_PHYSICALLY_LOCKED"; ...
         "CURRENT_BACKBONE_OPERATIONAL_REFERENCE"; ...
         "RMSE_ONLY_SELECTION_ALLOWED"; ...
         "PHI1_PRESERVATION_REQUIRED"; ...
         "LEGACY_WIDTH_ALIGNMENT_ALLOWED_AS_TRUTH"; ...
         "CANDIDATE_SET_DEFINED"; ...
         "DECISION_RULES_DEFINED"; ...
         "READY_FOR_BACKBONE_SELECTION_RUN"], ...
        [string(fPlanDefined); string(fSelectionReady); string(fCurrentPhysicalLocked); string(fCurrentOperationalRef); ...
         string(fRmseOnlyAllowed); string(fPhi1Required); string(fLegacyWidthTruthAllowed); ...
         string(fCandidateSetDefined); string(fDecisionRulesDefined); string(fReadyForRun)], ...
        ["Selection adjudication framework defined as planning stage."; ...
         "Run readiness remains PARTIAL until candidate ambiguities and penalties are locked in execution checklist."; ...
         "Current backbone remains not physically locked per prior phases."; ...
         "Current PT/CDF remains operational reference."; ...
         "RMSE-only selection explicitly forbidden."; ...
         "Phi1 preservation is a hard admissibility requirement."; ...
         "Legacy width/alignment cannot be canonical truth."; ...
         "Candidate family set is explicitly enumerated."; ...
         "Decision outcomes and actions are explicitly defined."; ...
         "Ready for selection run after pre-run checklist confirms no unresolved ambiguity."], ...
        'VariableNames', {'check','result','detail'});
    switchingWriteTableBothPaths(statusTbl, repoRoot, runTables, 'switching_backbone_selection_plan_status.csv');

    % Report
    lines = {};
    lines{end+1} = '# Stage S0: Full Switching backbone selection adjudication plan';
    lines{end+1} = '';
    lines{end+1} = '## Purpose';
    lines{end+1} = '- Define a rigorous decision-gated framework to select the controlling backbone before further Phase D mechanism interpretation.';
    lines{end+1} = '- Planning/specification only. No backbone comparison run is executed in S0.';
    lines{end+1} = '';
    lines{end+1} = '## Guardrails';
    lines{end+1} = '- No producer edits, no canonical identity changes, no canonical output replacement.';
    lines{end+1} = '- No claims/context/snapshot/query updates.';
    lines{end+1} = '- Legacy width/shift/alignment cannot be used as canonical truth.';
    lines{end+1} = '- Even if an alternative wins later, outcome is redesign-required track, not automatic replacement.';
    lines{end+1} = '';
    lines{end+1} = '## Candidate families included';
    for i = 1:numel(cand)
        lines{end+1} = sprintf('- `%s`', cand(i));
    end
    lines{end+1} = '';
    lines{end+1} = '## Hard admissibility stance';
    lines{end+1} = '- Phi1 preservation is mandatory.';
    lines{end+1} = '- RMSE-only wins are invalid.';
    lines{end+1} = '- No Phi2-fitted backbone term allowed.';
    lines{end+1} = '';
    lines{end+1} = '## Decision outcomes';
    lines{end+1} = '- CURRENT_ACCEPTED / REDESIGN_REQUIRED / INCONCLUSIVE / REOPEN_DECOMPOSITION defined with explicit triggers and actions.';
    lines{end+1} = '';
    lines{end+1} = '## Required status flags';
    lines{end+1} = sprintf('- BACKBONE_SELECTION_PLAN_DEFINED = %s', fPlanDefined);
    lines{end+1} = sprintf('- BACKBONE_SELECTION_READY_TO_RUN = %s', fSelectionReady);
    lines{end+1} = sprintf('- CURRENT_BACKBONE_PHYSICALLY_LOCKED = %s', fCurrentPhysicalLocked);
    lines{end+1} = sprintf('- CURRENT_BACKBONE_OPERATIONAL_REFERENCE = %s', fCurrentOperationalRef);
    lines{end+1} = sprintf('- RMSE_ONLY_SELECTION_ALLOWED = %s', fRmseOnlyAllowed);
    lines{end+1} = sprintf('- PHI1_PRESERVATION_REQUIRED = %s', fPhi1Required);
    lines{end+1} = sprintf('- LEGACY_WIDTH_ALIGNMENT_ALLOWED_AS_TRUTH = %s', fLegacyWidthTruthAllowed);
    lines{end+1} = sprintf('- CANDIDATE_SET_DEFINED = %s', fCandidateSetDefined);
    lines{end+1} = sprintf('- DECISION_RULES_DEFINED = %s', fDecisionRulesDefined);
    lines{end+1} = sprintf('- READY_FOR_BACKBONE_SELECTION_RUN = %s', fReadyForRun);
    lines{end+1} = '';
    lines{end+1} = '## Artifacts';
    lines{end+1} = '- `tables/switching_backbone_selection_candidate_families.csv`';
    lines{end+1} = '- `tables/switching_backbone_selection_admissibility_gates.csv`';
    lines{end+1} = '- `tables/switching_backbone_selection_metrics_plan.csv`';
    lines{end+1} = '- `tables/switching_backbone_selection_decision_rules.csv`';
    lines{end+1} = '- `tables/switching_backbone_selection_plan_status.csv`';
    lines{end+1} = '- `reports/switching_backbone_selection_adjudication_plan.md`';

    switchingWriteTextLinesFile(fullfile(runReports, [baseName '.md']), lines, 'run_switching_backbone_selection_adjudication_plan:WriteFail');
    switchingWriteTextLinesFile(fullfile(repoRoot, 'reports', 'switching_backbone_selection_adjudication_plan.md'), lines, 'run_switching_backbone_selection_adjudication_plan:WriteFail');

    writeSwitchingExecutionStatus(runDir, {'SUCCESS'}, {'YES'}, {''}, height(famTbl), {'backbone selection adjudication plan completed'}, true);

catch ME
    if isempty(runDir)
        runDir = fullfile(repoRoot, 'results', 'switching', 'runs', 'run_switching_backbone_selection_adjudication_plan_failure');
        if exist(runDir, 'dir') ~= 7, mkdir(runDir); end
    end
    if exist(fullfile(runDir, 'tables'), 'dir') ~= 7, mkdir(fullfile(runDir, 'tables')); end
    if exist(fullfile(runDir, 'reports'), 'dir') ~= 7, mkdir(fullfile(runDir, 'reports')); end
    if exist(fullfile(repoRoot, 'tables'), 'dir') ~= 7, mkdir(fullfile(repoRoot, 'tables')); end
    if exist(fullfile(repoRoot, 'reports'), 'dir') ~= 7, mkdir(fullfile(repoRoot, 'reports')); end

    failMsg = char(string(ME.message));
    statusTbl = table( ...
        ["BACKBONE_SELECTION_PLAN_DEFINED"; "BACKBONE_SELECTION_READY_TO_RUN"; ...
         "CURRENT_BACKBONE_PHYSICALLY_LOCKED"; "CURRENT_BACKBONE_OPERATIONAL_REFERENCE"; ...
         "RMSE_ONLY_SELECTION_ALLOWED"; "PHI1_PRESERVATION_REQUIRED"; ...
         "LEGACY_WIDTH_ALIGNMENT_ALLOWED_AS_TRUTH"; "CANDIDATE_SET_DEFINED"; ...
         "DECISION_RULES_DEFINED"; "READY_FOR_BACKBONE_SELECTION_RUN"], ...
        ["NO"; "NO"; "NO"; "YES"; "NO"; "YES"; "NO"; "NO"; "NO"; "NO"], ...
        repmat(string(failMsg), 10, 1), ...
        'VariableNames', {'check','result','detail'});
    writetable(statusTbl, fullfile(runDir, 'tables', 'switching_backbone_selection_plan_status.csv'));
    writetable(statusTbl, fullfile(repoRoot, 'tables', 'switching_backbone_selection_plan_status.csv'));

    lines = {};
    lines{end+1} = '# Stage S0 backbone selection adjudication plan — FAILED';
    lines{end+1} = sprintf('- error_id: `%s`', ME.identifier);
    lines{end+1} = sprintf('- error_message: `%s`', ME.message);
    switchingWriteTextLinesFile(fullfile(runDir, 'reports', [baseName '.md']), lines, 'run_switching_backbone_selection_adjudication_plan:WriteFail');
    switchingWriteTextLinesFile(fullfile(repoRoot, 'reports', 'switching_backbone_selection_adjudication_plan.md'), lines, 'run_switching_backbone_selection_adjudication_plan:WriteFail');

    writeSwitchingExecutionStatus(runDir, {'FAILED'}, {'NO'}, {ME.message}, 0, {'backbone selection plan failed'}, true);
    rethrow(ME);
end
