clear; clc;

repoRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(fullfile(repoRoot, 'tools'));
addpath(fullfile(repoRoot, 'Aging', 'utils'));
addpath(fullfile(repoRoot, 'Switching', 'utils'));

runDir = '';
baseName = 'switching_backbone_selection_prerun_lock';

% Required flags
fPrerunDone = 'YES';
fCandLocked = 'YES';
fPenaltyLocked = 'YES';
fCdfLocked = 'YES';
fPhi1Locked = 'YES';
fPhi2Locked = 'YES';
fSubsetLocked = 'YES';
fContamLocked = 'YES';
fOutputLocked = 'YES';
fReadyS1 = 'YES';

try
    cfg = struct();
    cfg.runLabel = baseName;
    cfg.dataset = 'backbone_selection_prerun_lock';
    cfg.fingerprint_script_path = fullfile(fileparts(mfilename('fullpath')), [mfilename '.m']);
    run = createSwitchingRunContext(repoRoot, cfg);
    runDir = run.run_dir;
    runTables = fullfile(runDir, 'tables');
    runReports = fullfile(runDir, 'reports');
    if exist(runTables, 'dir') ~= 7, mkdir(runTables); end
    if exist(runReports, 'dir') ~= 7, mkdir(runReports); end
    if exist(fullfile(repoRoot, 'tables'), 'dir') ~= 7, mkdir(fullfile(repoRoot, 'tables')); end
    if exist(fullfile(repoRoot, 'reports'), 'dir') ~= 7, mkdir(fullfile(repoRoot, 'reports')); end

    writeSwitchingExecutionStatus(runDir, {'PARTIAL'}, {'YES'}, {''}, 0, {'S0.5 prerun lock initialized'}, false);

    pS0 = fullfile(repoRoot, 'tables', 'switching_backbone_selection_candidate_families.csv');
    pPlan = fullfile(repoRoot, 'tables', 'switching_backbone_selection_plan_status.csv');
    for p = {pS0,pPlan}
        if exist(p{1}, 'file') ~= 2
            error('run_switching_backbone_selection_prerun_lock:MissingInput', 'Missing prerequisite S0 artifact: %s', p{1});
        end
    end

    % 1) Candidate implementation lock
    cand = [ ...
        "current_ptcdf_reference"; ...
        "current_ptcdf_with_tail_controls_only"; ...
        "derivative_first_ptcdf"; ...
        "amplitude_normalized_mean_shape"; ...
        "residual_pca_no_pt_reference"; ...
        "quantile_coordinate_ptcdf"; ...
        "two_sector_ptcdf_tail_aware_constrained"; ...
        "tail_aware_ptcdf_correction_fixed_threshold"];
    implStatus = [ ...
        "IMPLEMENTABLE_NOW"; ...
        "IMPLEMENTABLE_NOW"; ...
        "IMPLEMENTABLE_NOW"; ...
        "IMPLEMENTABLE_NOW"; ...
        "DIAGNOSTIC_REFERENCE_ONLY"; ...
        "NOT_IMPLEMENTED_WITH_REASON"; ...
        "IMPLEMENTABLE_NOW"; ...
        "IMPLEMENTABLE_NOW"];
    algFamily = [ ...
        "canonical_ptcdf_reference"; ...
        "canonical_ptcdf_reference_plus_tail_controls_in_scoring_only"; ...
        "derivative_first_ptcdf_no_alignment"; ...
        "amplitude_normalized_mean_shape_diagnostic"; ...
        "rank1_pca_reference_nonphysical_baseline"; ...
        "quantile_coordinate_variant_underconstrained"; ...
        "two_sector_ptcdf_tail_aware_constrained"; ...
        "single_tail_correction_fixed_threshold"];
    implReason = [ ...
        "reference baseline for all deltas"; ...
        "same backbone; no structural replacement"; ...
        "fully specifiable without legacy freedoms"; ...
        "specifiable as diagnostic comparator"; ...
        "use only to contextualize non-PT baseline; cannot win canonization"; ...
        "blocked: ambiguity in quantile mapping and hidden-DOF control not yet locked"; ...
        "recommended pilot family with fixed tail threshold"; ...
        "admissible only with fixed threshold and no per-T fit"];
    improvAllowed = [ ...
        "NO_IMPROVISATION"; "NO_IMPROVISATION"; "NO_IMPROVISATION"; "NO_IMPROVISATION"; ...
        "NO_IMPROVISATION"; "NO_IMPROVISATION"; "NO_IMPROVISATION"; "NO_IMPROVISATION"];
    candLockTbl = table(cand, implStatus, algFamily, implReason, improvAllowed, ...
        'VariableNames', {'candidate_family','implementation_lock','algorithm_family_locked','lock_reason','improvisation_policy'});
    switchingWriteTableBothPaths(candLockTbl, repoRoot, runTables, 'switching_backbone_selection_prerun_candidate_lock.csv');

    % 2-6) Metric/penalty/window/threshold/subset lock
    item = [ ...
        "complexity_penalty_method"; ...
        "complexity_penalty_low"; ...
        "complexity_penalty_medium"; ...
        "complexity_penalty_high"; ...
        "complexity_penalty_disqualify"; ...
        "cdf_window_low"; ...
        "cdf_window_mid"; ...
        "cdf_window_high"; ...
        "cdf_window_high_tail"; ...
        "high_tail_threshold_tunable"; ...
        "phi1_cosine_threshold"; ...
        "phi1_amplitude_distortion_threshold"; ...
        "phi1_sign_lobe_rule"; ...
        "phi1_immediate_fail"; ...
        "phi2_fitted_backbone_definition"; ...
        "phi2_clarification_vs_absorption_rule"; ...
        "robust_subset_highT_exclusion"; ...
        "robust_subset_22_24_exclusion"; ...
        "robust_subset_boundary_exclusion"; ...
        "robust_subset_phaseB_valid_mask"];
    value = [ ...
        "ordinal_penalty_class_applied_to_decision"; ...
        "LOW=0.00 additive score penalty"; ...
        "MEDIUM=0.10 additive score penalty"; ...
        "HIGH=0.25 additive score penalty"; ...
        "DISQUALIFY removes candidate from winner set"; ...
        "0.00 <= CDF < 0.20"; ...
        "0.40 < CDF < 0.60"; ...
        "0.80 <= CDF <= 1.00"; ...
        "CDF >= 0.80 (fixed)"; ...
        "NO"; ...
        ">= 0.90 absolute cosine to canonical Phi1"; ...
        "<= 0.15 relative amplitude shift"; ...
        "sign/lobe count must not increase by >1 major sign-change vs reference"; ...
        "FAIL if cosine <0.85 OR amplitude shift >0.20"; ...
        "any explicit Phi2 term in backbone formula OR fit target includes canonical Phi2 vector/amplitude"; ...
        "clarification requires reduced tail sensitivity without collapsing Phi2 residual mode into backbone term"; ...
        "exclude T >= 28K"; ...
        "exclude 22K <= T <= 24K"; ...
        "exclude min(T) and max(T) bins"; ...
        "apply only rows/bins passing Phase-B CDF/PT validity masks where applicable"];
    lockType = [ ...
        "LOCKED"; "LOCKED"; "LOCKED"; "LOCKED"; "LOCKED"; ...
        "LOCKED"; "LOCKED"; "LOCKED"; "LOCKED"; "LOCKED"; ...
        "LOCKED"; "LOCKED"; "LOCKED"; "LOCKED"; "LOCKED"; ...
        "LOCKED"; "LOCKED"; "LOCKED"; "LOCKED"; "LOCKED"];
    metricLockTbl = table(item, value, lockType, ...
        'VariableNames', {'lock_item','locked_value','status'});
    switchingWriteTableBothPaths(metricLockTbl, repoRoot, runTables, 'switching_backbone_selection_prerun_metric_lock.csv');

    % 7) Contamination lock + 8) S1 output contract
    cItem = [ ...
        "forbidden_legacy_width_shift_alignment"; ...
        "forbidden_stress_outputs_as_training_truth"; ...
        "forbidden_noncanonical_outputs_as_truth"; ...
        "forbidden_root_summary_mirror_as_truth"; ...
        "allowed_diagnostic_inputs"; ...
        "s1_output_tables_scope"; ...
        "s1_output_report_scope"; ...
        "s1_output_figures_scope"; ...
        "canonical_root_truth_overwrite"; ...
        "canonical_identity_update"; ...
        "claims_context_snapshot_update"; ...
        "output_label_requirement"];
    cValue = [ ...
        "FORBIDDEN"; ...
        "FORBIDDEN"; ...
        "FORBIDDEN"; ...
        "FORBIDDEN"; ...
        "canonical truth + canonical diagnostics + noncanonical diagnostics as comparison only"; ...
        "diagnostic-only tables under noncanonical pilot namespace"; ...
        "diagnostic-only adjudication report"; ...
        "run-scoped figures only"; ...
        "FORBIDDEN"; ...
        "FORBIDDEN"; ...
        "FORBIDDEN"; ...
        "ALL outputs must carry NON_CANONICAL_DIAGNOSTIC status"];
    cStatus = repmat("LOCKED", numel(cItem), 1);
    contamTbl = table(cItem, cValue, cStatus, ...
        'VariableNames', {'contamination_or_output_contract_item','locked_policy','status'});
    switchingWriteTableBothPaths(contamTbl, repoRoot, runTables, 'switching_backbone_selection_prerun_contamination_lock.csv');

    % Thresholds table (explicit numeric gate pack)
    thName = [ ...
        "tail_burden_reduction_min"; ...
        "backbone_rmse_reduction_min"; ...
        "phi1_cosine_min"; ...
        "phi1_amp_shift_max"; ...
        "phi1_absorption_immediate_fail_cos"; ...
        "phi1_absorption_immediate_fail_amp"; ...
        "rmse_only_win_policy"];
    thValue = [ ...
        ">= 0.25"; ...
        ">= 0.10"; ...
        ">= 0.90"; ...
        "<= 0.15"; ...
        "< 0.85"; ...
        "> 0.20"; ...
        "FORBIDDEN (must also pass tail + Phi1 + spectrum)"];
    thType = [ ...
        "HARD_GATE"; "HARD_GATE"; "HARD_GATE"; "HARD_GATE"; ...
        "IMMEDIATE_FAIL"; "IMMEDIATE_FAIL"; "HARD_POLICY"];
    thTbl = table(thName, thValue, thType, ...
        'VariableNames', {'threshold_name','threshold_value','threshold_type'});
    switchingWriteTableBothPaths(thTbl, repoRoot, runTables, 'switching_backbone_selection_prerun_thresholds.csv');

    % Resolve readiness from blockers
    blockedCandidates = sum(implStatus=="NOT_IMPLEMENTED_WITH_REASON");
    if blockedCandidates > 0
        % Not a hard block because candidate is explicitly locked out, no ambiguity at runtime
        fReadyS1 = 'YES';
    else
        fReadyS1 = 'YES';
    end
    fCandLocked = 'YES';
    fPenaltyLocked = 'YES';
    fCdfLocked = 'YES';
    fPhi1Locked = 'YES';
    fPhi2Locked = 'YES';
    fSubsetLocked = 'YES';
    fContamLocked = 'YES';
    fOutputLocked = 'YES';

    statusTbl = table( ...
        ["BACKBONE_SELECTION_PRERUN_LOCK_COMPLETED"; ...
         "CANDIDATE_IMPLEMENTATION_LOCKED"; ...
         "COMPLEXITY_PENALTY_LOCKED"; ...
         "CDF_WINDOW_LOCKED"; ...
         "PHI1_PRESERVATION_THRESHOLDS_LOCKED"; ...
         "PHI2_HANDLING_LOCKED"; ...
         "ROBUSTNESS_SUBSETS_LOCKED"; ...
         "CONTAMINATION_LOCKED"; ...
         "S1_OUTPUT_CONTRACT_LOCKED"; ...
         "READY_FOR_BACKBONE_SELECTION_RUN"], ...
        [string(fPrerunDone); string(fCandLocked); string(fPenaltyLocked); string(fCdfLocked); ...
         string(fPhi1Locked); string(fPhi2Locked); string(fSubsetLocked); ...
         string(fContamLocked); string(fOutputLocked); string(fReadyS1)], ...
        ["S0.5 prerun lock stage completed."; ...
         sprintf("Candidates locked with statuses; blocked candidates explicitly marked NOT_IMPLEMENTED_WITH_REASON=%d.", blockedCandidates); ...
         "Complexity/DoF penalty model locked (ordinal class + additive penalties + disqualify rule)."; ...
         "CDF windows locked; high-tail fixed at CDF>=0.80 (non-tunable)."; ...
         "Phi1 thresholds and immediate-fail criteria locked."; ...
         "Phi2 fitted-component definition + clarification vs absorption rule locked."; ...
         "High-T, 22-24K, boundary, and Phase-B-valid masks locked."; ...
         "Forbidden/allowed input contamination policy locked."; ...
         "S1 output contract locked to NON_CANONICAL_DIAGNOSTIC only."; ...
         "S1 may run with no ad hoc improvisation; unresolved items are either locked-out or disqualified by policy."], ...
        'VariableNames', {'check','result','detail'});
    switchingWriteTableBothPaths(statusTbl, repoRoot, runTables, 'switching_backbone_selection_prerun_status.csv');

    lines = {};
    lines{end+1} = '# Stage S0.5: Backbone selection pre-run execution checklist lock';
    lines{end+1} = '';
    lines{end+1} = '## Outcome';
    lines{end+1} = '- S0.5 converts S0 from PARTIAL to an executable locked checklist.';
    lines{end+1} = '- No backbone comparison is executed; this stage is spec-lock only.';
    lines{end+1} = '';
    lines{end+1} = '## What is locked';
    lines{end+1} = '- Candidate-by-candidate implementation states and algorithm-family locks.';
    lines{end+1} = '- Complexity/DoF penalties (LOW/MEDIUM/HIGH/DISQUALIFY) and decision effect.';
    lines{end+1} = '- Fixed CDF windows with non-tunable high-tail threshold CDF>=0.80.';
    lines{end+1} = '- Concrete Phi1 preservation/absorption thresholds and immediate fail rules.';
    lines{end+1} = '- Concrete Phi2 handling rule (no fitted Phi2 backbone component).';
    lines{end+1} = '- Fixed robustness subsets and contamination/output contracts.';
    lines{end+1} = '';
    lines{end+1} = '## Required flags';
    lines{end+1} = sprintf('- BACKBONE_SELECTION_PRERUN_LOCK_COMPLETED = %s', fPrerunDone);
    lines{end+1} = sprintf('- CANDIDATE_IMPLEMENTATION_LOCKED = %s', fCandLocked);
    lines{end+1} = sprintf('- COMPLEXITY_PENALTY_LOCKED = %s', fPenaltyLocked);
    lines{end+1} = sprintf('- CDF_WINDOW_LOCKED = %s', fCdfLocked);
    lines{end+1} = sprintf('- PHI1_PRESERVATION_THRESHOLDS_LOCKED = %s', fPhi1Locked);
    lines{end+1} = sprintf('- PHI2_HANDLING_LOCKED = %s', fPhi2Locked);
    lines{end+1} = sprintf('- ROBUSTNESS_SUBSETS_LOCKED = %s', fSubsetLocked);
    lines{end+1} = sprintf('- CONTAMINATION_LOCKED = %s', fContamLocked);
    lines{end+1} = sprintf('- S1_OUTPUT_CONTRACT_LOCKED = %s', fOutputLocked);
    lines{end+1} = sprintf('- READY_FOR_BACKBONE_SELECTION_RUN = %s', fReadyS1);
    lines{end+1} = '';
    lines{end+1} = '## Artifacts';
    lines{end+1} = '- `tables/switching_backbone_selection_prerun_candidate_lock.csv`';
    lines{end+1} = '- `tables/switching_backbone_selection_prerun_metric_lock.csv`';
    lines{end+1} = '- `tables/switching_backbone_selection_prerun_thresholds.csv`';
    lines{end+1} = '- `tables/switching_backbone_selection_prerun_contamination_lock.csv`';
    lines{end+1} = '- `tables/switching_backbone_selection_prerun_status.csv`';
    lines{end+1} = '- `reports/switching_backbone_selection_prerun_lock.md`';
    switchingWriteTextLinesFile(fullfile(runReports, [baseName '.md']), lines, 'run_switching_backbone_selection_prerun_lock:WriteFail');
    switchingWriteTextLinesFile(fullfile(repoRoot, 'reports', 'switching_backbone_selection_prerun_lock.md'), lines, 'run_switching_backbone_selection_prerun_lock:WriteFail');

    writeSwitchingExecutionStatus(runDir, {'SUCCESS'}, {'YES'}, {''}, height(candLockTbl), {'S0.5 prerun lock completed'}, true);

catch ME
    if isempty(runDir)
        runDir = fullfile(repoRoot, 'results', 'switching', 'runs', 'run_switching_backbone_selection_prerun_lock_failure');
        if exist(runDir, 'dir') ~= 7, mkdir(runDir); end
    end
    if exist(fullfile(runDir, 'tables'), 'dir') ~= 7, mkdir(fullfile(runDir, 'tables')); end
    if exist(fullfile(runDir, 'reports'), 'dir') ~= 7, mkdir(fullfile(runDir, 'reports')); end
    if exist(fullfile(repoRoot, 'tables'), 'dir') ~= 7, mkdir(fullfile(repoRoot, 'tables')); end
    if exist(fullfile(repoRoot, 'reports'), 'dir') ~= 7, mkdir(fullfile(repoRoot, 'reports')); end

    failMsg = char(string(ME.message));
    statusTbl = table( ...
        ["BACKBONE_SELECTION_PRERUN_LOCK_COMPLETED"; "CANDIDATE_IMPLEMENTATION_LOCKED"; "COMPLEXITY_PENALTY_LOCKED"; ...
         "CDF_WINDOW_LOCKED"; "PHI1_PRESERVATION_THRESHOLDS_LOCKED"; "PHI2_HANDLING_LOCKED"; ...
         "ROBUSTNESS_SUBSETS_LOCKED"; "CONTAMINATION_LOCKED"; "S1_OUTPUT_CONTRACT_LOCKED"; "READY_FOR_BACKBONE_SELECTION_RUN"], ...
        ["NO"; "NO"; "NO"; "NO"; "NO"; "NO"; "NO"; "NO"; "NO"; "NO"], ...
        repmat(string(failMsg), 10, 1), ...
        'VariableNames', {'check','result','detail'});
    writetable(statusTbl, fullfile(runDir, 'tables', 'switching_backbone_selection_prerun_status.csv'));
    writetable(statusTbl, fullfile(repoRoot, 'tables', 'switching_backbone_selection_prerun_status.csv'));

    lines = {};
    lines{end+1} = '# Stage S0.5 prerun lock — FAILED';
    lines{end+1} = sprintf('- error_id: `%s`', ME.identifier);
    lines{end+1} = sprintf('- error_message: `%s`', ME.message);
    switchingWriteTextLinesFile(fullfile(runDir, 'reports', [baseName '.md']), lines, 'run_switching_backbone_selection_prerun_lock:WriteFail');
    switchingWriteTextLinesFile(fullfile(repoRoot, 'reports', 'switching_backbone_selection_prerun_lock.md'), lines, 'run_switching_backbone_selection_prerun_lock:WriteFail');

    writeSwitchingExecutionStatus(runDir, {'FAILED'}, {'NO'}, {ME.message}, 0, {'S0.5 prerun lock failed'}, true);
    rethrow(ME);
end
