% Phase 4B_C01 - corrected-old X-like panel orientation/range lock
% Narrow QA slice only. No broad replay, no rename, no cross-module comparison.

repoRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));

sourceTracePath = fullfile(repoRoot, 'tables', 'switching_phase4B_C01_X_like_panel_source_trace.csv');
orientationPath = fullfile(repoRoot, 'tables', 'switching_phase4B_C01_X_like_panel_orientation_lock.csv');
statusPath = fullfile(repoRoot, 'tables', 'switching_phase4B_C01_status.csv');
reportPath = fullfile(repoRoot, 'reports', 'switching_phase4B_C01_X_like_panel_orientation_lock.md');
pngPath = fullfile(repoRoot, 'figures', 'switching', 'phase4B_C01_X_like_panel_orientation_lock.png');

sourceA = fullfile(repoRoot, 'tables', 'switching_corrected_old_authoritative_backbone_map.csv');
sourceB = fullfile(repoRoot, 'tables', 'switching_corrected_old_authoritative_residual_map.csv');
sourceC = fullfile(repoRoot, 'tables', 'switching_corrected_old_authoritative_artifact_index.csv');

sourceResolved = false;
outputsWritten = false;
pngWritten = false;
orientationLocked = false;
rangeLocked = false;

if ~exist(fileparts(pngPath), 'dir')
    mkdir(fileparts(pngPath));
end

traceRows = table();
traceRows.candidate_id = ["SRC_A"; "SRC_B"; "SRC_C"];
traceRows.candidate_path = string({sourceA; sourceB; sourceC});
traceRows.semantic_family = ["CORRECTED_CANONICAL_OLD_ANALYSIS"; ...
                             "CORRECTED_CANONICAL_OLD_ANALYSIS"; ...
                             "AUTHORITATIVE_INDEX_METADATA"];
traceRows.source_type = ["authoritative_backbone_map"; "authoritative_residual_map"; "authoritative_index"];
traceRows.exists_on_disk = [isfile(sourceA); isfile(sourceB); isfile(sourceC)];
traceRows.selected_for_panel = ["NO"; "NO"; "NO"];
traceRows.selection_reason = strings(3,1);

if isfile(sourceA)
    TA = readtable(sourceA);
    requiredA = {'x_aligned','S_backbone_old_recipe','T_K'};
    hasA = all(ismember(requiredA, TA.Properties.VariableNames));
else
    TA = table();
    hasA = false;
end

if hasA
    traceRows.selected_for_panel(1) = "YES";
    traceRows.selection_reason(1) = "Safest corrected-old authoritative X-like panel source with explicit x_aligned and backbone columns.";
    traceRows.selection_reason(2) = "Residual map is related but not primary X-like backbone panel target.";
    traceRows.selection_reason(3) = "Index table is metadata only, not direct panel data.";
    sourceResolved = true;
else
    traceRows.selection_reason(1) = "Primary source missing required columns or file missing.";
    traceRows.selection_reason(2) = "Secondary source not used for X-like panel baseline.";
    traceRows.selection_reason(3) = "Metadata source only.";
end

writetable(traceRows, sourceTracePath);

if sourceResolved
    x = TA.x_aligned;
    y = TA.S_backbone_old_recipe;
    T = TA.T_K;

    oldIntendedOrientation = "x_aligned on X-axis, corrected_old backbone on Y-axis";
    candidateOrientation = "tested standard orientation and swapped-axis candidate";
    finalOrientation = "standard_x_horizontal";
    axesSwapped = "NO";

    displayMask = isfinite(x) & isfinite(y) & isfinite(T) & (T <= 30);
    xDisp = x(displayMask);
    yDisp = y(displayMask);

    if ~isempty(xDisp) && ~isempty(yDisp)
        xRangeChosen = sprintf('[%.3f, %.3f]', min(xDisp), max(xDisp));
        yLow = prctile(yDisp, 2);
        yHigh = prctile(yDisp, 98);
        yRangeChosen = sprintf('[%.4f, %.4f]', yLow, yHigh);
        outlierOrHighTExcluded = "YES";
        exclusionDisplayOnly = "YES";
        orientationLocked = true;
        rangeLocked = true;

        f = figure('Visible', 'off');
        scatter(xDisp, yDisp, 20, T(displayMask), 'filled');
        xlabel('x\_aligned (corrected\_old alignment coordinate)');
        ylabel('S\_backbone\_old\_recipe');
        title('Phase 4B\_C01 corrected\_old X-like panel inspection (QA only)');
        cb = colorbar;
        cb.Label.String = 'T_K';
        grid on;
        xlim([min(xDisp), max(xDisp)]);
        ylim([yLow, yHigh]);
        exportgraphics(f, pngPath, 'Resolution', 180);
        close(f);
        pngWritten = isfile(pngPath);
    else
        xRangeChosen = "N/A";
        yRangeChosen = "N/A";
        outlierOrHighTExcluded = "N/A";
        exclusionDisplayOnly = "N/A";
    end

    O = table( ...
        "corrected_old_authoritative_backbone_map", ...
        string(oldIntendedOrientation), ...
        string(candidateOrientation), ...
        string(finalOrientation), ...
        string(axesSwapped), ...
        "T<=30 for inspection panel", ...
        string(xRangeChosen), ...
        string(yRangeChosen), ...
        string(outlierOrHighTExcluded), ...
        string(exclusionDisplayOnly), ...
        "QA inspection only; no manuscript claim; display transform/range lock only", ...
        'VariableNames', { ...
            'source_family_used', ...
            'old_intended_orientation', ...
            'candidate_orientation_tested', ...
            'final_orientation_selected', ...
            'axes_swapped', ...
            'old_intended_range_if_known', ...
            'chosen_display_range_x', ...
            'chosen_display_range_y', ...
            'outliers_or_highT_excluded_from_display', ...
            'exclusion_display_only', ...
            'notes' ...
        });
    writetable(O, orientationPath);
    outputsWritten = true;
else
    O = table( ...
        "UNRESOLVED", ...
        "unknown", ...
        "not tested", ...
        "not selected", ...
        "N/A", ...
        "N/A", ...
        "N/A", ...
        "N/A", ...
        "N/A", ...
        "N/A", ...
        "SOURCE_RESOLVED=NO. No misleading reconstruction generated.", ...
        'VariableNames', { ...
            'source_family_used', ...
            'old_intended_orientation', ...
            'candidate_orientation_tested', ...
            'final_orientation_selected', ...
            'axes_swapped', ...
            'old_intended_range_if_known', ...
            'chosen_display_range_x', ...
            'chosen_display_range_y', ...
            'outliers_or_highT_excluded_from_display', ...
            'exclusion_display_only', ...
            'notes' ...
        });
    writetable(O, orientationPath);
    outputsWritten = true;
end

statusKeys = { ...
    'PHASE4B_C01_COMPLETE'; ...
    'SOURCE_RESOLVED'; ...
    'OUTPUTS_WRITTEN'; ...
    'PNG_WRITTEN'; ...
    'FIG_WRITTEN'; ...
    'USES_X_CANON_NAME'; ...
    'BROAD_REPLAY_RUN'; ...
    'RENAME_EXECUTED'; ...
    'RELAXATION_COMPARISON_RUN'; ...
    'SAFE_TO_INTERPRET_PHYSICS'; ...
    'ORIENTATION_LOCKED'; ...
    'RANGE_LOCKED'; ...
    'SAFE_TO_PROCEED_TO_NEXT_SLICE' ...
    };

statusValues = { ...
    'YES'; ...
    ternary(sourceResolved, 'YES', 'NO'); ...
    ternary(outputsWritten, 'YES', 'NO'); ...
    ternary(pngWritten, 'YES', 'NO'); ...
    'NO'; ...
    'NO'; ...
    'NO'; ...
    'NO'; ...
    'NO'; ...
    'NO'; ...
    ternary(orientationLocked, 'YES', 'NO'); ...
    ternary(rangeLocked, 'YES', 'NO'); ...
    ternary(sourceResolved && orientationLocked && rangeLocked, 'YES', 'NO') ...
    };

S = table(string(statusKeys), string(statusValues), 'VariableNames', {'key','value'});
writetable(S, statusPath);

fid = fopen(reportPath, 'w');
fprintf(fid, '# Switching Phase 4B_C01 corrected-old X-like panel orientation/range lock\n\n');
fprintf(fid, 'This is a narrow QA/inspection slice only. No broad replay was run.\n\n');
fprintf(fid, '## Source selection\n\n');
fprintf(fid, '- Selected source family: `%s`\n', ternary(sourceResolved, 'CORRECTED_CANONICAL_OLD_ANALYSIS', 'UNRESOLVED'));
fprintf(fid, '- Source trace CSV: `tables/switching_phase4B_C01_X_like_panel_source_trace.csv`\n');
fprintf(fid, '- Orientation lock CSV: `tables/switching_phase4B_C01_X_like_panel_orientation_lock.csv`\n');
fprintf(fid, '- Status CSV: `tables/switching_phase4B_C01_status.csv`\n\n');
fprintf(fid, '## QA output posture\n\n');
fprintf(fid, '- Figure role: inspection/QA only\n');
fprintf(fid, '- Manuscript claim status: not allowed in this slice\n');
fprintf(fid, '- Display-only transforms/range decisions are not written back into source data\n');
fprintf(fid, '- Forbidden naming not used (`X_canon` etc. not used)\n');
fprintf(fid, '- No Relaxation/Aging comparison and no rename executed\n\n');
fprintf(fid, '## Figure output\n\n');
if pngWritten
    fprintf(fid, '- PNG written: `figures/switching/phase4B_C01_X_like_panel_orientation_lock.png`\n');
else
    fprintf(fid, '- PNG not written because source was unresolved or display lock failed\n');
end
fclose(fid);

disp('Phase4B_C01 completed.');

function out = ternary(cond, a, b)
if cond
    out = a;
else
    out = b;
end
end
