% SWITCHING NAMESPACE / EVIDENCE WARNING
% NAMESPACE_ID: DIAGNOSTIC_FORENSIC — mode hierarchy synthesis from certified audit CSVs (no new SVD here)
% EVIDENCE_STATUS: AUDIT_AGGREGATION — NOT primary manuscript physics reconstruction
% BACKBONE_FORMULA: N/A — reads prior audit matrices
% SVD_INPUT: N/A in this script (aggregation only)
% COORDINATE_GRID: N/A
% SAFE_USE: gate/boundary tables for mode claims; cite certification CSV dependency
% UNSAFE_USE: promoting rank2/3 to primary claims without charter; conflating with CORRECTED_CANONICAL_OLD_ANALYSIS authoritative maps
% NOT_MAIN_MANUSCRIPT_EVIDENCE_IF_APPLICABLE: synthesis report is supporting governance evidence class
% CURRENT_STATE_ENTRYPOINT: reports/switching_corrected_canonical_current_state.md
clear; clc;

% Mode-hierarchy synthesis audit — aggregates certified audit outputs only (no new decomposition/physics analysis).

repoRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(fullfile(repoRoot, 'tools'));
addpath(fullfile(repoRoot, 'Aging', 'utils'));
addpath(fullfile(repoRoot, 'Switching', 'utils'));

if exist(fullfile(repoRoot, 'tables'), 'dir') ~= 7, mkdir(fullfile(repoRoot, 'tables')); end
if exist(fullfile(repoRoot, 'reports'), 'dir') ~= 7, mkdir(fullfile(repoRoot, 'reports')); end

outMatrix = fullfile(repoRoot, 'tables', 'switching_mode_hierarchy_evidence_matrix.csv');
outBoundary = fullfile(repoRoot, 'tables', 'switching_mode_claim_boundary.csv');
outScaleCmp = fullfile(repoRoot, 'tables', 'switching_mode_scale_leakage_comparison.csv');
outStatus = fullfile(repoRoot, 'tables', 'switching_mode_hierarchy_status.csv');
outReport = fullfile(repoRoot, 'reports', 'switching_mode_hierarchy_synthesis_audit.md');

% ------------------------------ Evidence gate ------------------------------
gatePath = fullfile(repoRoot, 'tables', 'switching_mode_evidence_certification_status.csv');
if exist(gatePath, 'file') ~= 2
    error('run_switching_mode_hierarchy_synthesis_audit:MissingGate', ...
        'Missing switching_mode_evidence_certification_status.csv.');
end
gate = readtable(gatePath, 'TextType', 'string');
need = { ...
    'MODE_EVIDENCE_CERTIFICATION_COMPLETE', ...
    'FAILED_PHI2_REPLACEMENT_EXCLUDED', ...
    'CRITICAL_MODE_AUDITS_CERTIFIED', ...
    'CANONICAL_ONLY_NEXT_AUDIT_EVIDENCE_AVAILABLE', ...
    'SAFE_TO_RUN_PHI3_RELATIONSHIP_AUDITS' ...
    };
for i = 1:numel(need)
    ix = find(strcmpi(strtrim(gate.check), need{i}), 1);
    if isempty(ix) || upper(strtrim(gate.result(ix))) ~= "YES"
        error('run_switching_mode_hierarchy_synthesis_audit:GateFailed', ...
            'Evidence gate failed at %s.', need{i});
    end
end

% ------------------------------ Required inputs -----------------------------
reqFiles = { ...
    fullfile(repoRoot, 'tables', 'switching_canonical_identity.csv'), ...
    fullfile(repoRoot, 'tables', 'switching_low_mode_physical_interpretation.csv'), ...
    fullfile(repoRoot, 'reports', 'switching_phi1_physical_meaning_audit.md'), ...
    fullfile(repoRoot, 'reports', 'switching_phi1_high_current_weakening_audit.md'), ...
    fullfile(repoRoot, 'reports', 'switching_phi2_physical_meaning_audit.md'), ...
    fullfile(repoRoot, 'tables', 'switching_phi2_deformation_geometry.csv'), ...
    fullfile(repoRoot, 'reports', 'switching_phi2_map_contribution_audit.md'), ...
    fullfile(repoRoot, 'reports', 'switching_kappa2_observable_anatomy_audit.md'), ...
    fullfile(repoRoot, 'tables', 'switching_kappa2_scale_sensitivity_status.csv'), ...
    fullfile(repoRoot, 'tables', 'rank3_classification_status.csv'), ...
    fullfile(repoRoot, 'tables', 'rank3_reconstruction_importance_status.csv'), ...
    fullfile(repoRoot, 'reports', 'switching_phi3_mode_relationship_geometry.md'), ...
    fullfile(repoRoot, 'reports', 'switching_kappa3_amplitude_anatomy.md'), ...
    fullfile(repoRoot, 'reports', 'switching_kappa3_amplitude_scale_sensitivity.md'), ...
    fullfile(repoRoot, 'tables', 'switching_stage_e5_status.csv'), ...
    fullfile(repoRoot, 'tables', 'switching_stage_e5b_claim_boundary_review.csv') ...
    };
for i = 1:numel(reqFiles)
    if exist(reqFiles{i}, 'file') ~= 2
        error('run_switching_mode_hierarchy_synthesis_audit:MissingInput', ...
            'Missing required certified input: %s', reqFiles{i});
    end
end

idRaw = readcell(fullfile(repoRoot, 'tables', 'switching_canonical_identity.csv'), 'Delimiter', ',');
canonicalRunId = "";
for r = 2:size(idRaw, 1)
    key = strtrim(string(idRaw{r, 1}));
    key = regexprep(key, "^\xFEFF", "");
    if strcmpi(key, "CANONICAL_RUN_ID")
        canonicalRunId = strtrim(string(idRaw{r, 2}));
        break;
    end
end
if strlength(canonicalRunId) == 0
    error('run_switching_mode_hierarchy_synthesis_audit:MissingRunId', ...
        'CANONICAL_RUN_ID missing.');
end

% ----------------------------- Load core evidence ---------------------------
lowMode = readtable(fullfile(repoRoot, 'tables', 'switching_low_mode_physical_interpretation.csv'), 'TextType', 'string');
k2Scale = readtable(fullfile(repoRoot, 'tables', 'switching_kappa2_scale_sensitivity_status.csv'), 'TextType', 'string');
e5 = readtable(fullfile(repoRoot, 'tables', 'switching_stage_e5_status.csv'), 'TextType', 'string');
e5b = readtable(fullfile(repoRoot, 'tables', 'switching_stage_e5b_claim_boundary_review.csv'), 'TextType', 'string');
r3c = readtable(fullfile(repoRoot, 'tables', 'rank3_classification_status.csv'), 'TextType', 'string');
r3i = readtable(fullfile(repoRoot, 'tables', 'rank3_reconstruction_importance_status.csv'), 'TextType', 'string');

phi1Meaning = string(fileread(fullfile(repoRoot, 'reports', 'switching_phi1_physical_meaning_audit.md')));
phi1Weak = string(fileread(fullfile(repoRoot, 'reports', 'switching_phi1_high_current_weakening_audit.md')));
phi2Meaning = string(fileread(fullfile(repoRoot, 'reports', 'switching_phi2_physical_meaning_audit.md')));
phi2Map = string(fileread(fullfile(repoRoot, 'reports', 'switching_phi2_map_contribution_audit.md')));
k2Anat = string(fileread(fullfile(repoRoot, 'reports', 'switching_kappa2_observable_anatomy_audit.md')));
phi3Rel = string(fileread(fullfile(repoRoot, 'reports', 'switching_phi3_mode_relationship_geometry.md')));
k3Anat = string(fileread(fullfile(repoRoot, 'reports', 'switching_kappa3_amplitude_anatomy.md')));
k3Scale = string(fileread(fullfile(repoRoot, 'reports', 'switching_kappa3_amplitude_scale_sensitivity.md')));

% ----------------------- Derived interpretation statuses --------------------
PHI1_INTERPRETATION_STATUS = triReady( ...
    contains(phi1Meaning, "PHI1_HAS_PHYSICAL_SIGNATURE=PARTIAL") || contains(phi1Meaning, "PHI1_MECHANISM_CLAIM_ALLOWED=NO"), ...
    contains(phi1Weak, "PHI1_PHYSICAL_WEAKENING_SUPPORTED=PARTIAL"), ...
    false);

KAPPA1_INTERPRETATION_STATUS = triReady( ...
    false, ...
    true, ...
    false);

PHI2_INTERPRETATION_STATUS = triReady( ...
    contains(phi2Meaning, "PHI2_IS_STABLE_PHYSICAL_COMPONENT** = PARTIAL"), ...
    contains(phi2Map, "PHI2_IS_MAP_IMPORTANT** = **YES"), ...
    false);

KAPPA2_INTERPRETATION_STATUS = triReady( ...
    getCheck(k2Scale, "KAPPA2_TAIL_ASYMMETRY_DRIVER_STABLE") == "YES" && getCheck(k2Scale, "KAPPA2_DRIVER_IS_GENERIC_SCALE") == "NO", ...
    getCheck(k2Scale, "KAPPA2_INTERPRETATION_AFTER_SCALE_TEST") == "mixed" || getCheck(k2Scale, "KAPPA2_SCALE_LEAKAGE_RISK") == "PARTIAL", ...
    false);

PHI3_INTERPRETATION_STATUS = triDiag( ...
    contains(phi3Rel, "PHI3_SHOULD_REMAIN_DIAGNOSTIC = YES"), ...
    contains(phi3Rel, "PHI3_IS_LOW_MODE_DEFORMATION = PARTIAL"), ...
    false);

KAPPA3_INTERPRETATION_STATUS = triDiag( ...
    contains(k3Scale, "KAPPA3_INTERPRETATION_AFTER_SCALE_TEST = generic_scale") || contains(k3Scale, "KAPPA3_SHOULD_REMAIN_DIAGNOSTIC = YES"), ...
    contains(k3Anat, "KAPPA3_IS_LOW_MODE_AMPLITUDE_COUPLED = PARTIAL"), ...
    false);

KAPPA2_MORE_PHYSICAL_THAN_KAPPA3 = ynp( ...
    getCheck(k2Scale, "KAPPA2_DRIVER_IS_GENERIC_SCALE") == "NO" && contains(k3Scale, "KAPPA3_DRIVER_IS_GENERIC_SCALE = YES"), ...
    getCheck(k2Scale, "KAPPA2_INTERPRETATION_AFTER_SCALE_TEST") == "mixed" && contains(k3Scale, "KAPPA3_SCALE_LEAKAGE_RISK = YES"));

MODE_HIERARCHY_READY_FOR_CONSERVATIVE_WRITING = ynp( ...
    getCheckE5B(e5b, "READY_FOR_LIMITED_CLAIM_READINESS") == "YES" && getCheckE5B(e5b, "CLAIMS_ALLOWED_LIMITED") == "YES", ...
    getCheck(e5, "READY_FOR_CLAIM_READINESS_REVIEW") == "NO" && getCheckE5B(e5b, "CLAIMS_ALLOWED_LIMITED") == "YES");

FULL_PHYSICAL_CLOSURE_CLAIM_ALLOWED = ternary( ...
    getCheckE5B(e5b, "RANK2_FULL_CLOSURE_CLAIM_ALLOWED") == "YES", ...
    "YES", "NO");

% -------------------------- Evidence matrix table ---------------------------
objects = ["PT-CDF backbone";"Phi1";"kappa1";"Phi2";"kappa2";"Phi3";"kappa3"];
reconImportance = [ ...
    "PRIMARY (backbone reference)"; ...
    "HIGH (rank-1 gain strong)"; ...
    "HIGH (drives Phi1 contribution vs T)"; ...
    "HIGH (rank-2 gain strong, map-important)"; ...
    "HIGH (amplitude gate for Phi2 map gains)"; ...
    "PARTIAL (rank-3 gain transition-localized, diagnostic)"; ...
    "PARTIAL (diagnostic amplitude; not promoted)" ...
    ];
shapeInterp = [ ...
    "PT-CDF structural backbone"; ...
    "High-current localized correction shape"; ...
    "N/A amplitude coordinate"; ...
    "Tail-structured deformation component"; ...
    "N/A amplitude coordinate"; ...
    "Transition-related diagnostic residual shape"; ...
    "N/A amplitude coordinate" ...
    ];
ampInterp = [ ...
    "N/A"; ...
    "Scaled by kappa1"; ...
    "Leading correction amplitude"; ...
    "Scaled by kappa2"; ...
    "Mixed tail/asymmetry + S_peak influence"; ...
    "Scaled by diagnostic kappa3"; ...
    "Generic-scale prone diagnostic amplitude" ...
    ];
scaleLeakRisk = [ ...
    "LOW"; ...
    "PARTIAL"; ...
    "PARTIAL"; ...
    "PARTIAL"; ...
    char(getCheck(k2Scale, "KAPPA2_SCALE_LEAKAGE_RISK")); ...
    "HIGH (diagnostic only)"; ...
    "YES" ...
    ];
transitionDep = [ ...
    "Global backbone"; ...
    "Exception at 32K noted"; ...
    "Moderate"; ...
    "Transition-localized gain YES"; ...
    "PARTIAL"; ...
    "YES (rank3 transition mode)"; ...
    "PARTIAL" ...
    ];
indVsDef = [ ...
    "Foundational structure"; ...
    "Primary deformation correction"; ...
    "Amplitude of primary correction"; ...
    "Secondary deformation correction"; ...
    "Amplitude of secondary deformation"; ...
    "Diagnostic residual deformation"; ...
    "Diagnostic residual amplitude" ...
    ];
allowedClaim = [ ...
    "Baseline PT-CDF reference layer is physically meaningful"; ...
    "Phi1 is stable leading correction (bounded claims)"; ...
    "kappa1 is leading observable amplitude coordinate"; ...
    "Phi2 is meaningful tail-structured subleading correction"; ...
    "kappa2 tracks subleading residual burden with scale caveats"; ...
    "Phi3 may be used diagnostically for residual structure"; ...
    "kappa3 may be used diagnostically only, not as physical closure coordinate" ...
    ];
forbiddenOverclaim = [ ...
    "Backbone alone closes full mechanism"; ...
    "Phi1 provides standalone mechanism closure"; ...
    "kappa1 alone is full physical state variable"; ...
    "Phi2 independently closes hierarchy"; ...
    "kappa2 is purely unique physical coordinate without scale leakage risk"; ...
    "Phi3 is promoted physical mode"; ...
    "kappa3 is robust physical coordinate after scale controls" ...
    ];

matrixTbl = table(objects, reconImportance, shapeInterp, ampInterp, scaleLeakRisk, transitionDep, indVsDef, allowedClaim, forbiddenOverclaim, ...
    'VariableNames', {'object','reconstruction_importance','shape_interpretation','amplitude_interpretation','scale_leakage_risk','transition_dependence','independence_vs_deformation_status','allowed_physical_claim','forbidden_overclaim'});
writetable(matrixTbl, outMatrix);

% ----------------------- Scale-leakage comparison table ---------------------
k2Interp = getCheck(k2Scale, "KAPPA2_INTERPRETATION_AFTER_SCALE_TEST");
k2Leak = getCheck(k2Scale, "KAPPA2_SCALE_LEAKAGE_RISK");
k2Generic = getCheck(k2Scale, "KAPPA2_DRIVER_IS_GENERIC_SCALE");
k2Residual = getCheck(k2Scale, "KAPPA2_DRIVER_IS_RESIDUAL_ENERGY");

k3Generic = extractReportFlag(k3Scale, "KAPPA3_DRIVER_IS_GENERIC_SCALE");
k3Residual = extractReportFlag(k3Scale, "KAPPA3_DRIVER_IS_RESIDUAL_ENERGY");
k3Leak = extractReportFlag(k3Scale, "KAPPA3_SCALE_LEAKAGE_RISK");
k3Interp = extractReportFlag(k3Scale, "KAPPA3_INTERPRETATION_AFTER_SCALE_TEST");

cmpTbl = table();
cmpTbl.metric = [ ...
    "driver_generic_scale"; ...
    "driver_residual_energy"; ...
    "scale_leakage_risk"; ...
    "post_scale_interpretation"; ...
    "physical_claim_after_scale"; ...
    "does_kappa3_collapse_more_to_generic_scale_than_kappa2"; ...
    "does_kappa2_remain_more_deformation_specific_than_kappa3" ...
    ];
cmpTbl.kappa2 = [k2Generic; k2Residual; k2Leak; k2Interp; "PARTIAL"; ...
    ynp(k3Generic=="YES" && k2Generic~="YES", false); ...
    KAPPA2_MORE_PHYSICAL_THAN_KAPPA3];
cmpTbl.kappa3 = [k3Generic; k3Residual; k3Leak; k3Interp; "DIAGNOSTIC"; ...
    ynp(k3Generic=="YES" && k2Generic~="YES", false); ...
    KAPPA2_MORE_PHYSICAL_THAN_KAPPA3];
cmpTbl.comparison_verdict = [ ...
    cmpText(k2Generic, k3Generic); ...
    cmpText(k2Residual, k3Residual); ...
    cmpText(k2Leak, k3Leak); ...
    cmpText(k2Interp, k3Interp); ...
    "kappa3 remains diagnostic-only; kappa2 remains mixed/partial physical"; ...
    ynp(k3Generic=="YES" && k2Generic~="YES", false); ...
    KAPPA2_MORE_PHYSICAL_THAN_KAPPA3 ...
    ];
writetable(cmpTbl, outScaleCmp);

% -------------------------- Claim-boundary table ----------------------------
boundaryTbl = table();
boundaryTbl.claim_class = [ ...
    "strong_claim";"strong_claim"; ...
    "partial_claim";"partial_claim";"partial_claim"; ...
    "diagnostic_only_claim";"diagnostic_only_claim"; ...
    "forbidden_claim";"forbidden_claim";"forbidden_claim"; ...
    "open_question";"open_question" ...
    ];
boundaryTbl.claim_item = [ ...
    "PT-CDF + Phi1 + Phi2 hierarchy is primary structural description"; ...
    "Phi2 map-level contribution is material including main domain"; ...
    "kappa2 is not reducible to generic scale, but remains mixed under scale controls"; ...
    "Phi1 high-current weakening interpretation holds in main domain with 32K exception"; ...
    "Rank3 adds transition-localized residual gain but does not close hierarchy"; ...
    "Phi3 is diagnostic residual correction only"; ...
    "kappa3 is diagnostic/generic-scale-prone after controls"; ...
    "Rank2 full closure claim"; ...
    "Promote rank3 to physical interpreted mode"; ...
    "Claim no higher-order interpretive risk"; ...
    "Whether one extra targeted transition-block exclusion could upgrade rank3 confidence"; ...
    "Whether kappa2 tail/asymmetry driver can be upgraded from PARTIAL to READY under stricter controls" ...
    ];
boundaryTbl.status = [ ...
    "YES";"YES"; ...
    "PARTIAL";"PARTIAL";"PARTIAL"; ...
    "YES";"YES"; ...
    "BLOCKED";"BLOCKED";"BLOCKED"; ...
    "OPEN";"OPEN" ...
    ];
boundaryTbl.evidence = [ ...
    "Stage E5 + E5B + low-mode interpretation"; ...
    "Phi2 map contribution audit"; ...
    "kappa2 scale sensitivity audit"; ...
    "Phi1 physical meaning + high-current weakening audits"; ...
    "rank3 reconstruction + classification + E5"; ...
    "Phi3 mode-relationship geometry"; ...
    "kappa3 amplitude anatomy + scale sensitivity"; ...
    "E5B RANK2_FULL_CLOSURE_CLAIM_ALLOWED=NO"; ...
    "E5B RANK3_PROMOTION_ALLOWED=NO"; ...
    "E5 HIGHER_ORDER_MODES_BLOCK_CLAIMS=PARTIAL + E5B blocked claim rows"; ...
    "E5B recommended_test minimum_additional_test"; ...
    "kappa2 scale sensitivity shows mixed interpretation" ...
    ];
writetable(boundaryTbl, outBoundary);

% ------------------------------ Status table -------------------------------
statusTbl = table( ...
    ["PHI1_INTERPRETATION_STATUS"; ...
     "KAPPA1_INTERPRETATION_STATUS"; ...
     "PHI2_INTERPRETATION_STATUS"; ...
     "KAPPA2_INTERPRETATION_STATUS"; ...
     "PHI3_INTERPRETATION_STATUS"; ...
     "KAPPA3_INTERPRETATION_STATUS"; ...
     "KAPPA2_MORE_PHYSICAL_THAN_KAPPA3"; ...
     "MODE_HIERARCHY_READY_FOR_CONSERVATIVE_WRITING"; ...
     "FULL_PHYSICAL_CLOSURE_CLAIM_ALLOWED"], ...
    [PHI1_INTERPRETATION_STATUS; ...
     KAPPA1_INTERPRETATION_STATUS; ...
     PHI2_INTERPRETATION_STATUS; ...
     KAPPA2_INTERPRETATION_STATUS; ...
     PHI3_INTERPRETATION_STATUS; ...
     KAPPA3_INTERPRETATION_STATUS; ...
     KAPPA2_MORE_PHYSICAL_THAN_KAPPA3; ...
     MODE_HIERARCHY_READY_FOR_CONSERVATIVE_WRITING; ...
     FULL_PHYSICAL_CLOSURE_CLAIM_ALLOWED], ...
    'VariableNames', {'check','result'});
writetable(statusTbl, outStatus);

% -------------------------------- Report -----------------------------------
lines = {};
lines{end+1} = '# Switching mode-hierarchy synthesis audit';
lines{end+1} = '';
lines{end+1} = '## Scope';
lines{end+1} = sprintf('- CANONICAL_RUN_ID: `%s`', canonicalRunId);
lines{end+1} = '- Switching only; certified canonical evidence only; failed Phi2 replacement excluded.';
lines{end+1} = '- This is a synthesis audit (claim-boundary consolidation), not new physics analysis.';
lines{end+1} = '';
lines{end+1} = '## Conservative hierarchy';
lines{end+1} = '- Primary structural layer: PT-CDF backbone.';
lines{end+1} = '- Primary residual correction: Phi1/kappa1.';
lines{end+1} = '- Deformation correction: Phi2/kappa2 (mixed after scale controls).';
lines{end+1} = '- Diagnostic correction: Phi3/kappa3 (not promoted; diagnostic-only).';
lines{end+1} = '';
lines{end+1} = '## Kappa2 vs Kappa3 after scale controls';
lines{end+1} = sprintf('- kappa2 interpretation: `%s` (generic-scale=%s, leakage=%s).', k2Interp, k2Generic, k2Leak);
lines{end+1} = sprintf('- kappa3 interpretation: `%s` (generic-scale=%s, leakage=%s).', k3Interp, k3Generic, k3Leak);
lines{end+1} = sprintf('- KAPPA2_MORE_PHYSICAL_THAN_KAPPA3 = %s', KAPPA2_MORE_PHYSICAL_THAN_KAPPA3);
lines{end+1} = '';
lines{end+1} = '## Final verdicts';
for i = 1:height(statusTbl)
    lines{end+1} = sprintf('- %s = %s', statusTbl.check(i), statusTbl.result(i));
end
lines{end+1} = '';
lines{end+1} = '## Outputs';
lines{end+1} = '- `tables/switching_mode_hierarchy_evidence_matrix.csv`';
lines{end+1} = '- `tables/switching_mode_claim_boundary.csv`';
lines{end+1} = '- `tables/switching_mode_scale_leakage_comparison.csv`';
lines{end+1} = '- `tables/switching_mode_hierarchy_status.csv`';

switchingWriteTextLinesFile(outReport, lines, 'run_switching_mode_hierarchy_synthesis_audit:WriteFail');
fprintf('[DONE] switching mode-hierarchy synthesis audit -> %s\n', outReport);

function v = getCheck(tbl, key)
v = "";
if ~ismember('check', tbl.Properties.VariableNames) || ~ismember('result', tbl.Properties.VariableNames)
    return;
end
idx = find(strcmpi(strtrim(string(tbl.check)), strtrim(string(key))), 1);
if ~isempty(idx)
    v = upper(strtrim(string(tbl.result(idx))));
end
end

function v = getCheckE5B(tbl, key)
v = "";
if ~ismember('item', tbl.Properties.VariableNames) || ~ismember('result', tbl.Properties.VariableNames)
    return;
end
idx = find(strcmpi(strtrim(string(tbl.item)), strtrim(string(key))), 1);
if ~isempty(idx)
    v = upper(strtrim(string(tbl.result(idx))));
end
end

function out = triReady(condReady, condPartial, condNo)
if condReady
    out = "READY";
elseif condNo
    out = "NO";
elseif condPartial
    out = "PARTIAL";
else
    out = "PARTIAL";
end
end

function out = triDiag(condDiag, condPartial, condNo)
if condDiag
    out = "DIAGNOSTIC";
elseif condNo
    out = "NO";
elseif condPartial
    out = "PARTIAL";
else
    out = "PARTIAL";
end
end

function out = ynp(condYes, condPartial)
if condYes
    out = "YES";
elseif condPartial
    out = "PARTIAL";
else
    out = "NO";
end
end

function out = ternary(cond, a, b)
if cond
    out = string(a);
else
    out = string(b);
end
end

function out = cmpText(a, b)
a = upper(strtrim(string(a)));
b = upper(strtrim(string(b)));
if a == b
    out = "MATCH";
elseif a == "YES" && b ~= "YES"
    out = "KAPPA2_STRONGER";
elseif b == "YES" && a ~= "YES"
    out = "KAPPA3_STRONGER";
else
    out = "MIXED";
end
end

function val = extractReportFlag(txt, key)
val = "UNKNOWN";
p = regexp(char(txt), [char(key) '\s*=\s*([A-Za-z_]+)'], 'tokens', 'once');
if ~isempty(p)
    val = upper(string(p{1}));
end
end
