clear; clc;

repoRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(fullfile(repoRoot, 'tools'));
addpath(fullfile(repoRoot, 'Aging', 'utils'));
addpath(fullfile(repoRoot, 'Switching', 'utils'));

run = struct();
runDir = '';
baseName = 'switching_tail_aware_backbone_redesign_spec';

% Required B1 flags (defaults; refined after evidence read)
fDesignRequired = 'YES';
fReplacementAllowedNow = 'NO';
fPilotReady = 'PARTIAL';
fRecommendedCandidate = 'two_sector_ptcdf_tail_aware_constrained';
fNoncanonicalInputsUsed = 'NO';
fNoncanonicalPromotedToTruth = 'NO';
fLegacyWidthAsTruth = 'NO';
fB1ContaminationRisk = 'PARTIAL';
fB1OutputCanonicalStatus = 'DESIGN_SPEC_ONLY';
fRiskAbsorbPhi1 = 'MEDIUM';
fRiskAbsorbPhi2 = 'HIGH';
fPhaseDBlocked = 'PARTIAL';
fCanRunDiagD = 'YES';
fFullCanonicalLock = 'NO';

try
    cfg = struct();
    cfg.runLabel = baseName;
    cfg.dataset = 'tail_aware_backbone_redesign_spec';
    cfg.fingerprint_script_path = fullfile(fileparts(mfilename('fullpath')), [mfilename '.m']);
    run = createSwitchingRunContext(repoRoot, cfg);
    runDir = run.run_dir;

    runTables = fullfile(runDir, 'tables');
    runReports = fullfile(runDir, 'reports');
    if exist(runTables, 'dir') ~= 7, mkdir(runTables); end
    if exist(runReports, 'dir') ~= 7, mkdir(runReports); end
    if exist(fullfile(repoRoot, 'tables'), 'dir') ~= 7, mkdir(fullfile(repoRoot, 'tables')); end
    if exist(fullfile(repoRoot, 'reports'), 'dir') ~= 7, mkdir(fullfile(repoRoot, 'reports')); end

    writeSwitchingExecutionStatus(runDir, {'PARTIAL'}, {'YES'}, {''}, 0, {'run initialized'}, false);

    % Locked operational canonical identity (read-only; no new analysis)
    idPath = fullfile(repoRoot, 'tables', 'switching_canonical_identity.csv');
    canonicalRunId = '';
    if exist(idPath, 'file') == 2
        idLines = readlines(idPath);
        for ii = 1:numel(idLines)
            ln = strtrim(string(idLines(ii)));
            if ln == "" || startsWith(lower(ln), "field,value"), continue; end
            tok = regexp(char(ln), '^([^,]+),(.+)$', 'tokens', 'once');
            if isempty(tok), continue; end
            if strcmpi(strtrim(tok{1}), 'CANONICAL_RUN_ID')
                canonicalRunId = strtrim(string(tok{2}));
                break;
            end
        end
    end
    if strlength(canonicalRunId) == 0
        canonicalRunId = "UNKNOWN_READ_IDENTITY_CSV";
    end

    % Evidence inputs: Phase-A frozen truth + accepted diagnostics only (read-only tables)
    pB = fullfile(repoRoot, 'tables', 'switching_backbone_validity_status.csv');
    pC = fullfile(repoRoot, 'tables', 'switching_mode_admissibility_status.csv');
    pB0 = fullfile(repoRoot, 'tables', 'switching_decomposition_foundation_status.csv');
    pStress = fullfile(repoRoot, 'tables', 'switching_backbone_stress_status.csv');
    pStressVar = fullfile(repoRoot, 'tables', 'switching_backbone_stress_variants.csv');
    pStressTail = fullfile(repoRoot, 'tables', 'switching_backbone_stress_tail_burden.csv');
    pTruthInv = fullfile(repoRoot, 'tables', 'switching_canonical_current_truth_inventory.csv');
    req = {pB, pC, pB0, pStress, pStressVar, pStressTail};
    for i = 1:numel(req)
        if exist(req{i}, 'file') ~= 2
            error('run_switching_tail_aware_backbone_redesign_spec:MissingInput', 'Missing required evidence table: %s', req{i});
        end
    end

    bMap = localReadStatusMap(pB);
    cMap = localReadStatusMap(pC);
    b0Map = localReadStatusMap(pB0);
    sMap = localReadStatusMap(pStress);
    readtable(pStressVar); %#ok<NASGU> validate file readable
    readtable(pStressTail); %#ok<NASGU>

    bBackbone = localGetMap(bMap, 'BACKBONE_VALID_FOR_RESIDUAL_ANALYSIS');
    bTail = localGetMap(bMap, 'BACKBONE_FAILURE_LOCALIZED_IN_HIGH_CDF_TAIL');
    cPhi1 = localGetMap(cMap, 'PHI1_ADMISSIBLE_PHYSICAL_MODE');
    cPhi2 = localGetMap(cMap, 'PHI2_ADMISSIBLE_PHYSICAL_MODE');
    cTail = localGetMap(cMap, 'PHI2_HIGH_CDF_TAIL_DOMINATED');
    cTailSurvive = localGetMap(cMap, 'PHI2_SURVIVES_TAIL_CONTROL');
    b0Cond = localGetMap(b0Map, 'CONDITIONAL_ON_MEASUREMENT_REGISTER');
    sRobust = localGetMap(sMap, 'CURRENT_PTCDF_BACKBONE_ROBUST');
    sTailNeed = localGetMap(sMap, 'TAIL_AWARE_BACKBONE_NEEDED');
    sAltOut = localGetMap(sMap, 'ALTERNATIVE_BACKBONE_OUTPERFORMS_CURRENT');

    fNoncanonicalInputsUsed = 'YES';
    fNoncanonicalPromotedToTruth = 'NO';
    fLegacyWidthAsTruth = 'NO';

    % --- Evidence classification (every B1 input source) ---
    evArtifact = [ ...
        "tables/switching_canonical_identity.csv"; ...
        "tables/switching_backbone_validity_status.csv"; ...
        "tables/switching_mode_admissibility_status.csv"; ...
        "tables/switching_decomposition_foundation_status.csv"; ...
        "tables/switching_backbone_stress_status.csv"; ...
        "tables/switching_backbone_stress_variants.csv"; ...
        "tables/switching_backbone_stress_tail_burden.csv"];
    evClass = [ ...
        "CANONICAL_TRUTH"; ...
        "CANONICAL_DIAGNOSTIC"; ...
        "CANONICAL_DIAGNOSTIC"; ...
        "CANONICAL_DIAGNOSTIC"; ...
        "NONCANONICAL_DIAGNOSTIC"; ...
        "NONCANONICAL_DIAGNOSTIC"; ...
        "NONCANONICAL_DIAGNOSTIC"];
    evUsed = [true; true; true; true; true; true; true];
    evNotes = strings(size(evArtifact));
    evNotes(1) = "Operational lock reference; CANONICAL_RUN_ID for resolver.";
    evNotes(2) = "Phase B backbone validity audit output.";
    evNotes(3) = "Phase C mode admissibility audit output.";
    evNotes(4) = "Phase B0 decomposition foundation audit output.";
    evNotes(5) = "Stress test aggregate flags; diagnostic variants only, not truth.";
    evNotes(6) = "Per-variant stress metrics; NONCANONICAL_DIAGNOSTIC only.";
    evNotes(7) = "Stress tail-burden table; NONCANONICAL_DIAGNOSTIC only.";
    if exist(pTruthInv, 'file') == 2
        evArtifact(end+1,1) = "tables/switching_canonical_current_truth_inventory.csv";
        evClass(end+1,1) = "CANONICAL_TRUTH";
        evUsed(end+1,1) = true;
        evNotes(end+1,1) = "Phase-A frozen truth inventory cross-check.";
    end
    evTbl = table(evArtifact, evClass, evUsed, evNotes, ...
        'VariableNames', {'artifact_path_or_key','classification','used_in_b1','notes'});
    switchingWriteTableBothPaths(evTbl, repoRoot, runTables, 'switching_tail_aware_backbone_evidence_classification.csv');

    % --- Contamination audit (explicit controls) ---
    caControl = [ ...
        "STRESS_VARIANTS_NONCANONICAL_ONLY"; ...
        "NO_PROMOTION_OF_DIAGNOSTIC_TO_TRUTH"; ...
        "LEGACY_WIDTH_ALIGNMENT_NOT_TRUTH"; ...
        "PHI2_NOT_FITTED_IN_BACKBONE_SPEC"; ...
        "B1_OUTPUT_NOT_CANONICAL"; ...
        "RECOMMENDATION_PILOT_ONLY_IF_NONCANONICAL_DEPENDENT"; ...
        "CANONICAL_RUN_ID_RESOLVER_USED"];
    caStatus = [ ...
        "PASS"; ...
        "PASS"; ...
        "PASS"; ...
        "PASS"; ...
        "PASS"; ...
        "PASS"; ...
        "PASS"];
    caNotes = [ ...
        "Stress tables classified NONCANONICAL_DIAGNOSTIC; used only as leads."; ...
        "B1 narrative and flags are design-spec only; no canonical backbone chosen."; ...
        "No legacy width/alignment tables read or cited as evidence in B1."; ...
        "Pilot spec forbids Phi2 inside backbone; design-only."; ...
        "B1_OUTPUT_CANONICAL_STATUS = DESIGN_SPEC_ONLY."; ...
        "Recommended pilot marked PILOT_ONLY where stress evidence informs ranking."; ...
        sprintf("Locked operational reference: CANONICAL_RUN_ID=%s", canonicalRunId)];
    contTbl = table(caControl, caStatus, caNotes, ...
        'VariableNames', {'contamination_control','status','audit_notes'});
    switchingWriteTableBothPaths(contTbl, repoRoot, runTables, 'switching_tail_aware_backbone_contamination_audit.csv');

    % --- Design constraints (unchanged policy set; evidence refs tightened) ---
    cName = [ ...
        "NO_WIDTH_SCALING"; ...
        "NO_ALIGNMENT_COORDINATES"; ...
        "NO_PER_T_ARBITRARY_SHIFT_SCALE"; ...
        "METADATA_GATED_INPUTS_ONLY"; ...
        "REPRODUCIBLE_PRODUCER_BEHAVIOR"; ...
        "MONOTONIC_COORDINATE_REQUIRED"; ...
        "NO_PHI2_FITTED_IN_BACKBONE"; ...
        "KEEP_CURRENT_CANONICAL_ACTIVE_REFERENCE"; ...
        "MEASUREMENT_LAYER_CONDITIONALITY"; ...
        "DIAGNOSTIC_ONLY_UNTIL_PILOT_PASS"; ...
        "NONCANONICAL_DIAGNOSTIC_NOT_TRUTH"; ...
        "PILOT_REQUIRED_BEFORE_CANONICAL_USE"];
    cRule = [ ...
        "forbidden"; ...
        "forbidden"; ...
        "forbidden"; ...
        "required"; ...
        "required"; ...
        "required"; ...
        "forbidden"; ...
        "required"; ...
        "required"; ...
        "required"; ...
        "required"; ...
        "required"];
    cReason = [ ...
        "prevents hidden collapse freedom"; ...
        "prevents legacy-like coordinate leakage"; ...
        "avoids overfitting mode structure"; ...
        "keeps truth-tier consistency"; ...
        "supports canonical reproducibility"; ...
        "maintains physical interpretability of PT/CDF-like coordinate"; ...
        "prevents baking mode-2 into backbone"; ...
        "current PT/CDF remains active operational reference per identity lock"; ...
        "measurement register partial lock conditions decomposition conclusions"; ...
        "alternative backbones remain diagnostic until formal replacement gate passes"; ...
        "stress-test and other noncanonical outputs are evidence leads only"; ...
        "no new backbone may enter canonical tier without pilot + gates"];
    cEvidence = [ ...
        "B0 + Phase-A scope"; ...
        "B0 + Phase-A scope"; ...
        "B0 decomposition foundation"; ...
        "Phase-A truth inventory"; ...
        "Canonical pipeline contract"; ...
        "Phase-B CDF/PT validity"; ...
        "Phase-C Phi2 partial + tail sensitive"; ...
        sprintf("switching_canonical_identity.csv CANONICAL_RUN_ID=%s", canonicalRunId); ...
        sprintf("B0 CONDITIONAL_ON_MEASUREMENT_REGISTER=%s", b0Cond); ...
        sprintf("Stress ALTERNATIVE_BACKBONE_OUTPERFORMS_CURRENT=%s (NONCANONICAL_DIAGNOSTIC)", sAltOut); ...
        "B1 contamination audit"; ...
        "B1 pilot_spec + replacement_criteria"];
    constraintsTbl = table(cName, cRule, cReason, cEvidence, ...
        'VariableNames', {'constraint_name','policy','design_reason','evidence_reference'});
    switchingWriteTableBothPaths(constraintsTbl, repoRoot, runTables, 'switching_tail_aware_backbone_design_constraints.csv');

    % --- Candidate families (includes current PT/CDF + tail controls only) ---
    fam = [ ...
        "tail_aware_ptcdf_correction"; ...
        "derivative_first_ptpdf"; ...
        "amplitude_normalized_mean_shape"; ...
        "two_sector_lowmid_plus_tail"; ...
        "quantile_coordinate_backbone"; ...
        "current_ptcdf_with_tail_controls_only"];
    evClassPrimary = [ ...
        "NONCANONICAL_DIAGNOSTIC"; ...
        "NONCANONICAL_DIAGNOSTIC"; ...
        "NONCANONICAL_DIAGNOSTIC"; ...
        "MIXED_CANONICAL_AND_NONCANONICAL_DIAGNOSTIC"; ...
        "CANONICAL_DIAGNOSTIC"; ...
        "CANONICAL_TRUTH"];
    physical = [ ...
        "PARTIAL"; ...
        "PARTIAL"; ...
        "PARTIAL"; ...
        "YES"; ...
        "PARTIAL"; ...
        "YES"];
    implRisk = [ ...
        "MEDIUM"; ...
        "MEDIUM"; ...
        "MEDIUM"; ...
        "MEDIUM"; ...
        "HIGH"; ...
        "LOW"];
    absorbPhi1 = [ ...
        "MEDIUM"; ...
        "MEDIUM"; ...
        "HIGH"; ...
        "MEDIUM"; ...
        "HIGH"; ...
        "LOW"];
    absorbPhi2 = [ ...
        "HIGH"; ...
        "MEDIUM"; ...
        "HIGH"; ...
        "MEDIUM"; ...
        "HIGH"; ...
        "LOW"];
    riskHiddenWidth = [ ...
        "MEDIUM"; ...
        "MEDIUM"; ...
        "HIGH"; ...
        "MEDIUM"; ...
        "HIGH"; ...
        "LOW"];
    expectedTail = [ ...
        "HIGH_REDUCTION"; ...
        "LOW_TO_MEDIUM_REDUCTION"; ...
        "HIGH_REDUCTION"; ...
        "HIGH_REDUCTION"; ...
        "MEDIUM_REDUCTION"; ...
        "ANALYSIS_SIDE_REDUCTION_ONLY"];
    preservesPhi1 = [ ...
        "YES"; ...
        "YES"; ...
        "PARTIAL"; ...
        "YES"; ...
        "PARTIAL"; ...
        "YES"];
    pilotAllowed = [ ...
        "YES"; ...
        "YES"; ...
        "YES"; ...
        "YES"; ...
        "PARTIAL"; ...
        "YES"];
    canonicalNowAllowed = [ ...
        "NO"; ...
        "NO"; ...
        "NO"; ...
        "NO"; ...
        "NO"; ...
        "YES"];
    pilotOnlyLead = [ ...
        "YES"; ...
        "YES"; ...
        "YES"; ...
        "YES"; ...
        "NO"; ...
        "NO"];
    stressEvidence = strings(size(fam));
    stressEvidence(1) = "NONCANONICAL: stress tail_aware variant improved RMSE/tail; not canonical-safe as truth.";
    stressEvidence(2) = "NONCANONICAL: derivative_first stress modest tail change; lead only.";
    stressEvidence(3) = "NONCANONICAL: mean-shape stress reduced tail but high Phi1-mixing risk; diagnostic only.";
    stressEvidence(4) = "CANONICAL: B/C/B0 localize failure to high-CDF tail. NONCANONICAL stress supports sector pilot lead.";
    stressEvidence(5) = "CANONICAL_DIAGNOSTIC/B0 plausibility; high hidden-DOF risk; not pilot-ready without extra spec.";
    stressEvidence(6) = "CANONICAL: retain current PT/CDF backbone; apply tail-window stratification and controls in analysis (no backbone replacement).";

    recommendation = [ ...
        "PILOT_ONLY_secondary"; ...
        "PILOT_ONLY_fallback"; ...
        "diagnostic_only_not_recommended_pilot"; ...
        "PILOT_ONLY_recommended"; ...
        "future_research"; ...
        "operational_mitigation_default"];

    famTbl = table(fam, evClassPrimary, physical, implRisk, absorbPhi1, absorbPhi2, riskHiddenWidth, expectedTail, preservesPhi1, ...
        pilotAllowed, canonicalNowAllowed, pilotOnlyLead, stressEvidence, recommendation, ...
        'VariableNames', {'candidate_family','evidence_source_class','physically_interpretable','implementation_risk', ...
        'risk_absorbing_phi1','risk_absorbing_phi2','risk_hidden_width_alignment_like_freedom','expected_tail_burden_effect', ...
        'preserves_phi1_interpretability','allowed_as_future_pilot','allowed_as_canonical_now','pilot_only_lead_dependency_on_noncanonical', ...
        'evidence_summary','b1_recommendation'});
    switchingWriteTableBothPaths(famTbl, repoRoot, runTables, 'switching_tail_aware_backbone_candidate_families.csv');

    % --- Pilot specification (explicit noncanonical / pilot gates) ---
    pField = [ ...
        "pilot_classification"; ...
        "pilot_name"; ...
        "candidate_family"; ...
        "canonical_run_reference"; ...
        "inputs"; ...
        "forbidden_operations"; ...
        "output_tables"; ...
        "output_status_flags"; ...
        "pass_criteria"; ...
        "fail_criteria"; ...
        "canonical_replacement_action"; ...
        "noncanonical_evidence_rule"; ...
        "notes"];
    pValue = [ ...
        "NON_CANONICAL_DIAGNOSTIC"; ...
        "pilot_two_sector_ptcdf_tail_constraint_v1"; ...
        "two_sector_lowmid_plus_tail"; ...
        sprintf("CANONICAL_RUN_ID=%s; compare metrics vs current PT/CDF from same gated S_long only.", canonicalRunId); ...
        "switching_canonical_S_long.csv + switching_canonical_phi1.csv + switching_mode_amplitudes_vs_T.csv (metadata-gated per validateCanonicalInputTable)"; ...
        "width scaling; alignment; per-T arbitrary shift/scale; phi2-fitted correction inside backbone; promoting stress outputs to truth"; ...
        "pilot_backbone_metrics.csv; pilot_backbone_tail_window.csv; pilot_mode_stability.csv"; ...
        "PILOT_PASSED, PILOT_TAIL_REDUCED, PILOT_PHI1_PRESERVED, PILOT_PHI2_CLARIFIED, PILOT_REQUIRED_BEFORE_CANONICAL_USE"; ...
        "Tail burden reduced vs reference AND Phi1 stability preserved AND no RMSE-only optimization AND no new coordinate DOF vs spec AND all gates in replacement_criteria"; ...
        "Any hidden width-like DOF, Phi1 absorption, metadata/replay failure, or stress-only justification without canonical cross-checks"; ...
        "NONE until independent rerun + measurement checkpoint; CURRENT_BACKBONE_REPLACEMENT_ALLOWED_NOW remains NO"; ...
        "Stress-test tables remain NONCANONICAL_DIAGNOSTIC; pilot must re-derive metrics on gated inputs, not copy stress artifacts as truth."; ...
        "Design-only. Current PT/CDF remains active operational reference until pilot passes all replacement criteria."];

    pilotTbl = table(pField, pValue, 'VariableNames', {'spec_field','spec_value'});
    switchingWriteTableBothPaths(pilotTbl, repoRoot, runTables, 'switching_tail_aware_backbone_pilot_spec.csv');

    % --- Replacement criteria (unchanged substance) ---
    rCrit = [ ...
        "improves_backbone_only_rmse"; ...
        "reduces_high_cdf_tail_burden"; ...
        "preserves_phi1_robustness"; ...
        "does_not_absorb_phi1_into_coordinate"; ...
        "residual_spectrum_stable"; ...
        "phi2_interpretation_improves_or_clarifies"; ...
        "metadata_gated_and_reproducible"; ...
        "measurement_register_checkpoint_passed"; ...
        "not_rmse_only_optimization"];
    rThreshold = repmat("strict_pass_required", 9, 1);
    rMethod = [ ...
        "compare against current PT/CDF reference on same CANONICAL_RUN_ID inputs"; ...
        "high/mid CDF burden ratio and high-CDF energy fraction"; ...
        "Phi1 cosine and mode1 dominance stability"; ...
        "audit coordinate DOF and per-T fit freedoms"; ...
        "mode1/mode2 fractions + subset consistency"; ...
        "tail-control and subset exclusion behavior"; ...
        "sidecar/gate/replay determinism checks"; ...
        "measurement-layer must not block; narrow PARTIAL implementation locks"; ...
        "reject if RMSE improves but tail/Phi1/stability worsen"];
    rDecision = [ ...
        "fail_any => reject replacement"; ...
        "fail_any => reject replacement"; ...
        "fail_any => reject replacement"; ...
        "fail_any => reject replacement"; ...
        "fail_any => reject replacement"; ...
        "fail_any => reject replacement"; ...
        "fail_any => reject replacement"; ...
        "fail_any => hold replacement as conditional"; ...
        "fail_any => reject replacement"];
    criteriaTbl = table(rCrit, rThreshold, rMethod, rDecision, ...
        'VariableNames', {'replacement_criterion','required_level','evaluation_method','decision_rule'});
    switchingWriteTableBothPaths(criteriaTbl, repoRoot, runTables, 'switching_tail_aware_backbone_replacement_criteria.csv');

    % Contamination risk: PARTIAL because B1 cites stress (noncanonical) for pilot ranking
    fB1ContaminationRisk = 'PARTIAL';

    statusTbl = table( ...
        {'TAIL_AWARE_BACKBONE_DESIGN_REQUIRED'; ...
         'CURRENT_BACKBONE_REPLACEMENT_ALLOWED_NOW'; ...
         'PILOT_BACKBONE_REDESIGN_READY'; ...
         'RECOMMENDED_BACKBONE_CANDIDATE'; ...
         'NONCANONICAL_DIAGNOSTIC_INPUTS_USED'; ...
         'NONCANONICAL_INPUTS_PROMOTED_TO_TRUTH'; ...
         'LEGACY_WIDTH_ALIGNMENT_USED_AS_TRUTH'; ...
         'B1_CONTAMINATION_RISK'; ...
         'B1_OUTPUT_CANONICAL_STATUS'; ...
         'RISK_OF_ABSORBING_PHI1'; ...
         'RISK_OF_ABSORBING_PHI2'; ...
         'PHASE_D_MECHANISM_INTERPRETATION_BLOCKED'; ...
         'CAN_RUN_DIAGNOSTIC_PHASE_D_ONLY'; ...
         'FULL_CANONICAL_LOCK_ALLOWED'}, ...
        {fDesignRequired; fReplacementAllowedNow; fPilotReady; fRecommendedCandidate; fNoncanonicalInputsUsed; ...
         fNoncanonicalPromotedToTruth; fLegacyWidthAsTruth; fB1ContaminationRisk; fB1OutputCanonicalStatus; fRiskAbsorbPhi1; ...
         fRiskAbsorbPhi2; fPhaseDBlocked; fCanRunDiagD; fFullCanonicalLock}, ...
        {sprintf('Phase-B=%s tail=%s; Phase-C Phi1=%s Phi2=%s tail_dom=%s tail_control=%s', bBackbone, bTail, cPhi1, cPhi2, cTail, cTailSurvive); ...
         'Current PT/CDF remains active operational reference until pilot + replacement gates pass.'; ...
         sprintf('Stress robustness=%s tail_needed=%s alt_outperforms=%s', sRobust, sTailNeed, sAltOut); ...
         'PILOT_ONLY: two-sector constrained PT/CDF tail family (see pilot_spec).'; ...
         'Stress status/variant/tail tables used as NONCANONICAL_DIAGNOSTIC leads only.'; ...
         'No stress or diagnostic artifact promoted to canonical truth in B1 outputs.'; ...
         'No legacy width/alignment tables used as evidence in B1.'; ...
         'Stress-informed pilot recommendation; mitigated by explicit classification + PILOT_ONLY labeling.'; ...
         'B1 is design specification only; not a canonical backbone selection.'; ...
         'Medium risk at sector boundary / residual reallocation.'; ...
         'High risk tail-aware designs absorb Phi2-like residual structure.'; ...
         'Mechanism-level claims blocked until pilot + replacement criteria resolved.'; ...
         'Diagnostic Phase D allowed with caveats; no canonical backbone replacement.'; ...
         sprintf('B0 physical lock NO; measurement conditional=%s.', b0Cond)}, ...
        'VariableNames', {'check','result','detail'});
    switchingWriteTableBothPaths(statusTbl, repoRoot, runTables, 'switching_tail_aware_backbone_design_status.csv');

    % Report
    lines = {};
    lines{end+1} = '# Phase B1 tail-aware backbone redesign specification (Switching)';
    lines{end+1} = '';
    lines{end+1} = '## Noncanonical contamination controls';
    lines{end+1} = '- Every evidence source is classified in `tables/switching_tail_aware_backbone_evidence_classification.csv`.';
    lines{end+1} = '- Stress-test artifacts are **NONCANONICAL_DIAGNOSTIC** only; they are not truth and are not promoted.';
    lines{end+1} = '- Legacy width/shift/alignment collapse is **not** used as valid evidence in B1 (EXCLUDED_UNSAFE as operational truth path).';
    lines{end+1} = '- Any recommendation that leans on stress metrics is labeled **PILOT_ONLY** and requires a future gated pilot.';
    lines{end+1} = '- B1 output status: **DESIGN_SPEC_ONLY** (not canonical).';
    lines{end+1} = '';
    lines{end+1} = '## Locked operational canonical reference';
    lines{end+1} = sprintf('- Resolver: `tables/switching_canonical_identity.csv` → **CANONICAL_RUN_ID** = `%s`.', canonicalRunId);
    lines{end+1} = '- Current PT/CDF backbone from that operational context remains the active reference until a pilot passes replacement gates.';
    lines{end+1} = '';
    lines{end+1} = '## Core design answers (summary)';
    lines{end+1} = '1. **High-CDF tail:** Phase B shows backbone failure localized there (residual energy concentrated vs mid-CDF); PT_pdf validity is PARTIAL at some T, compounding tail interpretation risk.';
    lines{end+1} = '2. **Stress variants that improved tail burden (diagnostic only):** tail_aware_backbone_diagnostic, amplitude_normalized_mean_shape, no_PT_PCA_reference — see stress tables; improvements are **canonical-unsafe as truth** (NONCANONICAL_DIAGNOSTIC).';
    lines{end+1} = '3. **Canonical-safe vs diagnostic:** only Phase B/C/B0 on gated canonical tables are canonical-truth/diagnostic tiers; stress improvements are **leads for pilot design only**.';
    lines{end+1} = '4. **Future backbone constraints:** see `switching_tail_aware_backbone_design_constraints.csv` (no width/alignment, no per-T arbitrary fit, metadata gate, monotonic coordinate, no Phi2 in backbone).';
    lines{end+1} = '5. **Tail-aware without forbidden freedoms:** yes in principle via **fixed-parameter** sector/tail extensions; sector boundaries must be globally specified, not per-T free fits.';
    lines{end+1} = '6. **Safest pilot family:** **two_sector_lowmid_plus_tail** (PILOT_ONLY) — best alignment with localized tail failure with controlled DOF; see `switching_tail_aware_backbone_pilot_spec.csv`.';
    lines{end+1} = '7. **Before canonical replacement:** pilot must pass all rows in `switching_tail_aware_backbone_replacement_criteria.csv` including not-RMSE-only rule and measurement checkpoint.';
    lines{end+1} = '';
    lines{end+1} = '## Evidence synthesis (canonical vs diagnostic)';
    lines{end+1} = sprintf('- Phase B (CANONICAL_DIAGNOSTIC): backbone validity=%s; tail localization=%s.', bBackbone, bTail);
    lines{end+1} = sprintf('- Phase C (CANONICAL_DIAGNOSTIC): Phi1=%s, Phi2=%s, tail dominated=%s, survives tail control=%s.', cPhi1, cPhi2, cTail, cTailSurvive);
    lines{end+1} = sprintf('- Phase B0 (CANONICAL_DIAGNOSTIC): operational PARTIAL, physical not locked, measurement-conditional=%s.', b0Cond);
    lines{end+1} = sprintf('- Stress test (NONCANONICAL_DIAGNOSTIC): robust=%s, tail-aware needed=%s, alt outperforms=%s.', sRobust, sTailNeed, sAltOut);
    lines{end+1} = '';
    lines{end+1} = '## Default operational mitigation';
    lines{end+1} = '- **current_ptcdf_with_tail_controls_only** remains valid without backbone replacement: stratified analysis, tail-window controls, and explicit caveats (allowed as canonical-now path for *continuing current backbone*).';
    lines{end+1} = '';
    lines{end+1} = '## Required status flags';
    lines{end+1} = sprintf('- TAIL_AWARE_BACKBONE_DESIGN_REQUIRED = %s', fDesignRequired);
    lines{end+1} = sprintf('- CURRENT_BACKBONE_REPLACEMENT_ALLOWED_NOW = %s', fReplacementAllowedNow);
    lines{end+1} = sprintf('- PILOT_BACKBONE_REDESIGN_READY = %s', fPilotReady);
    lines{end+1} = sprintf('- RECOMMENDED_BACKBONE_CANDIDATE = %s', fRecommendedCandidate);
    lines{end+1} = sprintf('- NONCANONICAL_DIAGNOSTIC_INPUTS_USED = %s', fNoncanonicalInputsUsed);
    lines{end+1} = sprintf('- NONCANONICAL_INPUTS_PROMOTED_TO_TRUTH = %s', fNoncanonicalPromotedToTruth);
    lines{end+1} = sprintf('- LEGACY_WIDTH_ALIGNMENT_USED_AS_TRUTH = %s', fLegacyWidthAsTruth);
    lines{end+1} = sprintf('- B1_CONTAMINATION_RISK = %s', fB1ContaminationRisk);
    lines{end+1} = sprintf('- B1_OUTPUT_CANONICAL_STATUS = %s', fB1OutputCanonicalStatus);
    lines{end+1} = sprintf('- RISK_OF_ABSORBING_PHI1 = %s', fRiskAbsorbPhi1);
    lines{end+1} = sprintf('- RISK_OF_ABSORBING_PHI2 = %s', fRiskAbsorbPhi2);
    lines{end+1} = sprintf('- PHASE_D_MECHANISM_INTERPRETATION_BLOCKED = %s', fPhaseDBlocked);
    lines{end+1} = sprintf('- CAN_RUN_DIAGNOSTIC_PHASE_D_ONLY = %s', fCanRunDiagD);
    lines{end+1} = sprintf('- FULL_CANONICAL_LOCK_ALLOWED = %s', fFullCanonicalLock);
    lines{end+1} = '';
    lines{end+1} = '## Artifacts';
    lines{end+1} = '- `tables/switching_tail_aware_backbone_candidate_families.csv`';
    lines{end+1} = '- `tables/switching_tail_aware_backbone_design_constraints.csv`';
    lines{end+1} = '- `tables/switching_tail_aware_backbone_evidence_classification.csv`';
    lines{end+1} = '- `tables/switching_tail_aware_backbone_contamination_audit.csv`';
    lines{end+1} = '- `tables/switching_tail_aware_backbone_pilot_spec.csv`';
    lines{end+1} = '- `tables/switching_tail_aware_backbone_replacement_criteria.csv`';
    lines{end+1} = '- `tables/switching_tail_aware_backbone_design_status.csv`';
    lines{end+1} = '- `reports/switching_tail_aware_backbone_redesign_spec.md`';

    switchingWriteTextLinesFile(fullfile(runReports, [baseName '.md']), lines, 'run_switching_tail_aware_backbone_redesign_spec:WriteFail');
    switchingWriteTextLinesFile(fullfile(repoRoot, 'reports', 'switching_tail_aware_backbone_redesign_spec.md'), lines, 'run_switching_tail_aware_backbone_redesign_spec:WriteFail');

    writeSwitchingExecutionStatus(runDir, {'SUCCESS'}, {'YES'}, {''}, height(famTbl), {'tail-aware backbone redesign spec completed'}, true);

catch ME
    if isempty(runDir)
        runDir = fullfile(repoRoot, 'results', 'switching', 'runs', 'run_switching_tail_aware_backbone_redesign_spec_failure');
        if exist(runDir, 'dir') ~= 7, mkdir(runDir); end
    end
    if exist(fullfile(runDir, 'tables'), 'dir') ~= 7, mkdir(fullfile(runDir, 'tables')); end
    if exist(fullfile(runDir, 'reports'), 'dir') ~= 7, mkdir(fullfile(runDir, 'reports')); end
    if exist(fullfile(repoRoot, 'tables'), 'dir') ~= 7, mkdir(fullfile(repoRoot, 'tables')); end
    if exist(fullfile(repoRoot, 'reports'), 'dir') ~= 7, mkdir(fullfile(repoRoot, 'reports')); end

    failMsg = char(string(ME.message));
    checks = { ...
        'TAIL_AWARE_BACKBONE_DESIGN_REQUIRED'; 'CURRENT_BACKBONE_REPLACEMENT_ALLOWED_NOW'; 'PILOT_BACKBONE_REDESIGN_READY'; ...
        'RECOMMENDED_BACKBONE_CANDIDATE'; 'NONCANONICAL_DIAGNOSTIC_INPUTS_USED'; 'NONCANONICAL_INPUTS_PROMOTED_TO_TRUTH'; ...
        'LEGACY_WIDTH_ALIGNMENT_USED_AS_TRUTH'; 'B1_CONTAMINATION_RISK'; 'B1_OUTPUT_CANONICAL_STATUS'; ...
        'RISK_OF_ABSORBING_PHI1'; 'RISK_OF_ABSORBING_PHI2'; 'PHASE_D_MECHANISM_INTERPRETATION_BLOCKED'; ...
        'CAN_RUN_DIAGNOSTIC_PHASE_D_ONLY'; 'FULL_CANONICAL_LOCK_ALLOWED'};
    results = {'YES'; 'NO'; 'NO'; 'unresolved_due_to_failure'; 'NO'; 'NO'; 'NO'; 'YES'; 'DESIGN_SPEC_ONLY'; ...
        'HIGH'; 'HIGH'; 'YES'; 'NO'; 'NO'};
    statusTbl = table(checks(:), results(:), repmat({failMsg}, numel(checks), 1), ...
        'VariableNames', {'check','result','detail'});
    writetable(statusTbl, fullfile(runDir, 'tables', 'switching_tail_aware_backbone_design_status.csv'));
    writetable(statusTbl, fullfile(repoRoot, 'tables', 'switching_tail_aware_backbone_design_status.csv'));

    lines = {};
    lines{end+1} = '# Phase B1 tail-aware backbone redesign specification — FAILED';
    lines{end+1} = sprintf('- error_id: `%s`', ME.identifier);
    lines{end+1} = sprintf('- error_message: `%s`', ME.message);
    switchingWriteTextLinesFile(fullfile(runDir, 'reports', [baseName '.md']), lines, 'run_switching_tail_aware_backbone_redesign_spec:WriteFail');
    switchingWriteTextLinesFile(fullfile(repoRoot, 'reports', 'switching_tail_aware_backbone_redesign_spec.md'), lines, 'run_switching_tail_aware_backbone_redesign_spec:WriteFail');

    writeSwitchingExecutionStatus(runDir, {'FAILED'}, {'NO'}, {ME.message}, 0, {'tail-aware backbone redesign spec failed'}, true);
    rethrow(ME);
end

function out = localGetMap(statusMap, key)
out = "";
if isKey(statusMap, upper(string(key)))
    out = statusMap(upper(string(key)));
end
end

function statusMap = localReadStatusMap(pathCsv)
statusMap = containers.Map('KeyType','char','ValueType','char');
lines = readlines(pathCsv);
for i = 1:numel(lines)
    ln = strtrim(string(lines(i)));
    if ln == "" || startsWith(lower(ln), "check,result")
        continue;
    end
    tok = regexp(char(ln), '^([^,]+),([^,]+),?.*$', 'tokens', 'once');
    if isempty(tok), continue; end
    k = upper(strtrim(string(tok{1})));
    v = upper(strtrim(string(tok{2})));
    statusMap(char(k)) = char(v);
end
end
